VMTK: TransferFunction Class Reference
TransferFunction Class Reference
#include <transferFunction.h>
Public Member Functions
void GetGrayScaleTF (int tag, int min, int max, int *elemSize, unsigned char **ptr)
void GetGrayScaleTF (int tag, int min, int max, int *elemSize, unsigned char **ptr, unsigned short nbtsalloc)
void GetRGBTF (int tag, int min, int max, int *elemSize, unsigned char **ptr)
Private Member Functions
void GetGrayScaleTFE (int min, int max, int *elemSize, unsigned char **ptr)
void GetGrayScaleTFL (int min, int max, int *elemSize, unsigned char **ptr)
Estimate linear transfer function from image char data values.
void GetGrayScaleTFS (int min, int max, int *elemSize, unsigned char **ptr)
void GetGrayScaleTFC (int min, int max, int *elemSize, unsigned char **ptr)
void GetGrayScaleTFD (int min, int max, int *elemSize, unsigned char **ptr, unsigned short nbitsalloc)
Detailed Description
Definition at line 28 of file transferFunction.h.
Member Function Documentation
GetGrayScaleTF() [1/2]
void TransferFunction::GetGrayScaleTF (int tag, int min, int max, int * elemSize, unsigned char ** ptr)
Definition at line 113 of file transferFunction.cpp.
References GetGrayScaleTFC(), GetGrayScaleTFE(), GetGrayScaleTFL(), and GetGrayScaleTFS().
Referenced by vmtkRender3D::generateTransferFunction().
{
  switch (tag) {
  case 0:
    GetGrayScaleTFE (min, max, elemSize, ptr);
    break;
  case 1:
    GetGrayScaleTFL (min, max, elemSize, ptr);
    break;
  case 2:
    GetGrayScaleTFS (min, max, elemSize, ptr);
    break;
  case 3:
    GetGrayScaleTFC (min, max, elemSize, ptr);
    break;
  }
 }
GetGrayScaleTF() [2/2]
void TransferFunction::GetGrayScaleTF (int tag, int min, int max, int * elemSize, unsigned char ** ptr, unsigned short nbtsalloc)
Definition at line 132 of file transferFunction.cpp.
References GetGrayScaleTFD().
{
  switch (tag) {
  case 4:
    GetGrayScaleTFD (min, max, elemSize, ptr, nbitsalloc);
    break;
  }
 }
GetGrayScaleTFC()
void TransferFunction::GetGrayScaleTFC (int min, int max, int * elemSize, unsigned char ** ptr) private
Definition at line 77 of file transferFunction.cpp.
References CUB.
Referenced by GetGrayScaleTF().
{
   double aux;
   *elemSize = max-min+2;
   *ptr = new unsigned char[*elemSize];
   aux = 1./(max-min+1);
   (*ptr)[0] = 0;
   for (int i = 1 ; i < *elemSize; i++)
     (*ptr)[i] = (unsigned char)(CUB(i*aux)*255);
 }
GetGrayScaleTFD()
void TransferFunction::GetGrayScaleTFD (int min, int max, int * elemSize, unsigned char ** ptr, unsigned short nbitsalloc) private
Definition at line 92 of file transferFunction.cpp.
Referenced by GetGrayScaleTF().
{
   double aux;
   int node1, node2;
   *elemSize = 256;
   *ptr = new unsigned char[*elemSize];
   aux = (1.*pow(2,8))/pow(2,nbitsalloc);
   node1 = (int)(min*aux);
   node2 = (int)(max*aux);
   for (int i = 0 ; i < node1; i++)
     (*ptr)[i] = 0;
   for (int i = node1 ; i < node2; i++)
     (*ptr)[i] = (unsigned char)((1.0*(i-node1))/(node2-node1)*255);
   for (int i = node2; i < *elemSize; i++)
     (*ptr)[i] = 0;
 }
GetGrayScaleTFE()
void TransferFunction::GetGrayScaleTFE (int min, int max, int * elemSize, unsigned char ** ptr) private
Estimate logarithmic transfer function from image char data values entry 0 is reserved to background intensity 0
Definition at line 37 of file transferFunction.cpp.
Referenced by GetGrayScaleTF().
{
   double aux;
   *elemSize = max-min+2;
   *ptr = new unsigned char[*elemSize];
   aux = 1./(max-min+1)*9;
   (*ptr)[0] = 0;
   for (int i = 1 ; i < *elemSize; i++)
     (*ptr)[i] = (unsigned char)(log(i*aux+1.)*255);
 }
GetGrayScaleTFL()
void TransferFunction::GetGrayScaleTFL (int min, int max, int * elemSize, unsigned char ** ptr) private
Estimate linear transfer function from image char data values.
Definition at line 51 of file transferFunction.cpp.
Referenced by GetGrayScaleTF().
{
   double aux;
   *elemSize = max-min+2;
   *ptr = new unsigned char[*elemSize];
   aux = 1./(max-min+1);
   (*ptr)[0] = 0;
   for (int i = 1 ; i < *elemSize; i++)
     (*ptr)[i] = (unsigned char)(i*aux*255);
 }
GetGrayScaleTFS()
void TransferFunction::GetGrayScaleTFS (int min, int max, int * elemSize, unsigned char ** ptr) private
Definition at line 64 of file transferFunction.cpp.
References SQR.
Referenced by GetGrayScaleTF().
{
   double aux;
   *elemSize = max-min+2;
   *ptr = new unsigned char[*elemSize];
   aux = 1./(max-min+1);
   (*ptr)[0] = 0;
   for (int i = 1 ; i < *elemSize; i++)
     (*ptr)[i] = (unsigned char)(SQR(i*aux)*255);
 }
GetRGBTF()
void TransferFunction::GetRGBTF (int tag, int min, int max, int * elemSize, unsigned char ** ptr)
Definition at line 142 of file transferFunction.cpp.
{
   // Variavel tag reservado para extensoes futuras
   unsigned char tabelaCor [] = {
     0, 0, 0,
     51, 0, 0,
     102, 0, 0,
     153, 0, 0,
     204, 0, 0,
     255, 0 , 0,
     255, 51, 0,
     255, 102, 0,
     255, 153, 0,
     255, 204, 0,
     255, 255, 0,
     204, 255, 0,
     153, 255, 0,
     102, 255, 0,
     51, 255, 0,
     0, 255, 0,
     0, 255, 51,
     0, 255, 102,
     0, 255, 153,
     0, 255, 204,
     0, 255, 255,
     0, 204, 255,
     0, 153, 255,
     0, 102, 255,
     0, 51, 255,
     0, 0, 255,
     51, 0, 255,
     102, 0, 255,
     153, 0, 255,
     204, 0, 255,
     255, 0, 255,
     255, 51, 255,
     255, 102, 255,
     255, 153, 255,
     255, 204, 244,
     255, 255, 255
   };
   *elemSize = sizeof(tabelaCor);
   *ptr = new unsigned char[*elemSize];
   memcpy (*ptr, tabelaCor, *elemSize);
 }
The documentation for this class was generated from the following files:
C:/vmtk_Multi-volume_Raycasting/include/transferFunction.h
C:/vmtk_Multi-volume_Raycasting/src/transferFunction.cpp