VMTK: Shaders Class Reference
Shaders Class Reference
#include <shaders.h>
Public Member Functions
GLuint carregueShaders (const char *vertexFileName, const char *fragmentFileName)
Private Member Functions
char * textFileRead (const char *fn)
textFileRead
int printOglError (char *file, int line)
printOglError
void printShaderInfoLog (GLuint obj)
printShaderInfoLog
void printProgramInfoLog (GLuint obj)
printProgramInfoLog
Detailed Description
Definition at line 39 of file shaders.h.
Member Function Documentation
carregueShaders()
GLuint Shaders::carregueShaders (const char * vertexFileName, const char * fragmentFileName)
Definition at line 115 of file shaders.cpp.
References printProgramInfoLog(), printShaderInfoLog(), and textFileRead().
Referenced by vmtkRender3D::initialize().
{
     const GLchar *vs = NULL,*fs = NULL;
     GLuint p,v,f;
     // Cria e compila shader de vértices
     v = glCreateShader(GL_VERTEX_SHADER);
     vs = (const GLchar *)textFileRead(vertexFileName);
     glShaderSource(v, 1, &vs, NULL);
     free((char *)vs);
     glCompileShader(v);
     printShaderInfoLog(v);
     // Cria e compila shader de fragmentos
     f = glCreateShader(GL_FRAGMENT_SHADER);
     fs = (const GLchar *)textFileRead(fragmentFileName);
     glShaderSource(f, 1, &fs,NULL);
     free((char *)fs);
     glCompileShader(f);
     printShaderInfoLog(f);
     // Cria um programa e anexa os shaders a ele
     p = glCreateProgram();
     glAttachShader(p,v);
     glAttachShader(p,f);
     // Liga os elementos do programa
     glLinkProgram(p);
     printProgramInfoLog(p);
     return(p);
 }
printOglError()
int Shaders::printOglError (char * file, int line) private
printOglError
Parameters
[in] file text string of file loaded.
[in] line line of text.
Returns
Returns 1 if an OpenGL error occurred, 0 otherwise.
Definition at line 58 of file shaders.cpp.
 {
     // Returns 1 if an OpenGL error occurred, 0 otherwise.
     GLenum glErr;
     int    retCode = 0;
     glErr = glGetError();
     while (glErr != GL_NO_ERROR)
     {
         printf("glError in file %s @ line %d: %s\n", file, line, gluErrorString(glErr));
         retCode = 1;
         glErr = glGetError();
     }
     return retCode;
 }
printProgramInfoLog()
void Shaders::printProgramInfoLog (GLuint obj) private
printProgramInfoLog
Parameters
[in] obj specifies the program object to be queried.
Definition at line 98 of file shaders.cpp.
Referenced by carregueShaders().
 {
     int infologLength = 0;
     int charsWritten  = 0;
     char *infoLog;
     glGetProgramiv(obj, GL_INFO_LOG_LENGTH,&infologLength);
     if (infologLength > 0)
     {
         infoLog = (char *)malloc(infologLength);
         glGetProgramInfoLog(obj, infologLength, &charsWritten, infoLog);
         printf("%s\n",infoLog);
         free(infoLog);
     }
 }
printShaderInfoLog()
void Shaders::printShaderInfoLog (GLuint obj) private
printShaderInfoLog
Parameters
[in] obj specifies the shader object to be queried.
Definition at line 74 of file shaders.cpp.
Referenced by carregueShaders().
 {
     int status = 0;
     int infologLength = 0;
     int charsWritten  = 0;
     char *infoLog;
     glGetShaderiv(obj, GL_INFO_LOG_LENGTH,&infologLength);
     if (infologLength > 0)
     {
         infoLog = (char *)malloc(infologLength);
         glGetShaderInfoLog(obj, infologLength, &charsWritten, infoLog);
         printf("%s\n",infoLog);
         free(infoLog);
     }
     glGetShaderiv(obj, GL_COMPILE_STATUS,&status);
     if (status)
         printf("Shader compiled\n");
     else
         printf("Shader not compiled\n");
 }
textFileRead()
char * Shaders::textFileRead (const char * fn) private
textFileRead
Parameters
[in] fn file name.
Returns
text string of file loaded.
Definition at line 28 of file shaders.cpp.
Referenced by carregueShaders().
{
   FILE *fp;
   char *content = NULL;
   int count=0;
   if (fn != NULL) {
     fp = fopen(fn,"rt");
     if (fp != NULL) {
       fseek(fp, 0, SEEK_END);
       count = ftell(fp);
       rewind(fp);
       if (count > 0) {
     content = (char *)malloc(sizeof(char) * (count+1));
     count = fread(content,sizeof(char),count,fp);
     content[count] = '\0';
       }
       fclose(fp);
     }
     else{
         std::cerr << "Shader not found!" << std::endl;
     }
   }
   return content;
 }
The documentation for this class was generated from the following files:
C:/vmtk_Multi-volume_Raycasting/include/shaders.h
C:/vmtk_Multi-volume_Raycasting/src/shaders.cpp