VMTK: VMATH_NAMESPACE::Matrix3< T > Class Template Reference
VMATH_NAMESPACE::Matrix3< T > Class Template Reference
#include <vmath.h>
Public Member Functions
Matrix3 ()
Matrix3 (const T *dt)
Matrix3 (const Matrix3< T > &src)
template<class FromT >
Matrix3 (const Matrix3< FromT > &src)
void identity ()
Vector3< T > vectorProductMatrix (const Vector3< T > &v) const
vectorProductMatrix: Multiplication function
bool operator== (const Matrix3< T > &rhs) const
bool operator!= (const Matrix3< T > &rhs) const
T & at (int x, int y)
const T & at (int x, int y) const
T & operator() (int i, int j)
const T & operator() (int i, int j) const
Matrix3< T > & operator= (const Matrix3< T > &rhs)
template<class FromT >
Matrix3< T > & operator= (const Matrix3< FromT > &rhs)
Matrix3< T > & operator= (const T *rhs)
Matrix3< T > operator+ (const Matrix3< T > &rhs) const
Matrix3< T > operator- (const Matrix3< T > &rhs) const
Matrix3< T > operator+ (T rhs) const
Matrix3< T > operator- (T rhs) const
Matrix3< T > operator* (T rhs) const
Matrix3< T > operator/ (T rhs) const
Vector3< T > operator* (const Vector3< T > &rhs) const
Matrix3< T > operator* (Matrix3< T > rhs) const
Matrix3< T > transpose ()
Matrix3< T > lerp (T fact, const Matrix3< T > &rhs) const
T det ()
Matrix3< T > inverse ()
operator T* ()
operator const T * () const
std::string toString () const
Static Public Member Functions
static Vector3< T > vectorProductMatrix (const Vector3< T > v, Matrix3< T > m)
vectorProductMatrix: Multiplication function
static Matrix3< T > createRotationAroundAxis (T xDeg, T yDeg, T zDeg)
static Vector3< T > getEulerAngles (Matrix3< T > R)
template<class It >
static Matrix3< T > fromOde (const It *mat)
template<class FromT >
static Matrix3< T > fromRowMajorArray (const FromT *arr)
template<class FromT >
static Matrix3< T > fromColumnMajorArray (const FromT *arr)
Public Attributes
T data [9]
Data stored in column major order.
Friends
std::ostream & operator<< (std::ostream &lhs, const Matrix3< T > &rhs)
Detailed Description
template<class T>
class VMATH_NAMESPACE::Matrix3< T >
Class for matrix 3x3.
Note
Data stored in this matrix are in column major order. This arrangement suits OpenGL. If you're using row major matrix, consider using fromRowMajorArray as way for construction Matrix3<T> instance.
Definition at line 1758 of file vmath.h.
Constructor & Destructor Documentation
Matrix3() [1/4]
template<class T> VMATH_NAMESPACE::Matrix3< T >::Matrix3 () inline
Creates identity matrix
Definition at line 1768 of file vmath.h.
     {
         for (int i = 0; i < 9; i++)
             data[i] = (i % 4) ? 0 : 1;
     }
Matrix3() [2/4]
template<class T> VMATH_NAMESPACE::Matrix3< T >::Matrix3 (const T * dt) inline
Copy matrix values from array (these data must be in column major order!)
Definition at line 1778 of file vmath.h.
     {
         std::memcpy(data, dt, sizeof(T) * 9);
     }
Matrix3() [3/4]
template<class T> VMATH_NAMESPACE::Matrix3< T >::Matrix3 (const Matrix3< T > & src) inline
Copy constructor.
Parameters
src Data source for new created instance of Matrix3
Definition at line 1787 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         std::memcpy(data, src.data, sizeof(T) * 9);
     }
Matrix3() [4/4]
template<class T> template<class FromT > VMATH_NAMESPACE::Matrix3< T >::Matrix3 (const Matrix3< FromT > & src) inline
Copy casting constructor.
Parameters
src Data source for new created instance of Matrix3
Definition at line 1797 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         for (int i = 0; i < 9; i++)
         {
             data[i] = static_cast<T>(src.data[i]);
         }
     }
Member Function Documentation
at() [1/2]
template<class T> T& VMATH_NAMESPACE::Matrix3< T >::at (int x, int y) inline
Get reference to element at position (x,y).
Parameters
x Number of column (0..2)
y Number of row (0..2)
Definition at line 2006 of file vmath.h.
References VMATH_NAMESPACE::Vector2< T >::y.
Referenced by VMATH_NAMESPACE::Matrix4< T >::createMat4FromMat3(), VMATH_NAMESPACE::Matrix3< T >::createRotationAroundAxis(), VMATH_NAMESPACE::Matrix3< T >::fromOde(), VMATH_NAMESPACE::Matrix3< T >::getEulerAngles(), VMATH_NAMESPACE::Matrix3< T >::inverse(), VMATH_NAMESPACE::Matrix3< T >::operator*(), VMATH_NAMESPACE::Quaternion< T >::rotMatrix(), VMATH_NAMESPACE::Matrix4< T >::setRotation(), VMATH_NAMESPACE::Matrix3< T >::transpose(), and VMATH_NAMESPACE::Matrix3< T >::vectorProductMatrix().
     {
         assert(x >= 0 && x < 3);
         assert(y >= 0 && y < 3);
         return data[x * 3 + y];
     }
at() [2/2]
template<class T> const T& VMATH_NAMESPACE::Matrix3< T >::at (int x, int y) const inline
Get constant reference to element at position (x,y).
Parameters
x Number of column (0..2)
y Number of row (0..2)
Definition at line 2018 of file vmath.h.
References VMATH_NAMESPACE::Vector2< T >::y.
     {
         assert(x >= 0 && x < 3);
         assert(y >= 0 && y < 3);
         return data[x * 3 + y];
     }
createRotationAroundAxis()
template<class T> static Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::createRotationAroundAxis (T xDeg, T yDeg, T zDeg) inline static
Creates rotation matrix by rotation around axis.
Parameters
xDeg Angle (in degrees) of rotation around axis X.
yDeg Angle (in degrees) of rotation around axis Y.
zDeg Angle (in degrees) of rotation around axis Z.
Definition at line 1854 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::at(), and DEG2RAD.
     {
         T xRads(DEG2RAD(xDeg));
         T yRads(DEG2RAD(yDeg));
         T zRads(DEG2RAD(zDeg));
         Matrix3<T> ma, mb, mc;
         float ac = cos(xRads);
         float as = sin(xRads);
         float bc = cos(yRads);
         float bs = sin(yRads);
         float cc = cos(zRads);
         float cs = sin(zRads);
         ma.at(1, 1) = ac;
         ma.at(2, 1) = as;
         ma.at(1, 2) = -as;
         ma.at(2, 2) = ac;
         mb.at(0, 0) = bc;
         mb.at(2, 0) = -bs;
         mb.at(0, 2) = bs;
         mb.at(2, 2) = bc;
         mc.at(0, 0) = cc;
         mc.at(1, 0) = cs;
         mc.at(0, 1) = -cs;
         mc.at(1, 1) = cc;
         Matrix3<T> ret = ma * mb * mc;
         return ret;
     }
det()
template<class T> T VMATH_NAMESPACE::Matrix3< T >::det () inline
Definition at line 2228 of file vmath.h.
     {
         return +at(0, 0) * at(1, 1) * at(2, 2) + at(0, 1) * at(1, 2) * at(2, 0) + at(0, 2) * at(1, 0) * at(2, 1)
                 - at(0, 0) * at(1, 2) * at(2, 1) - at(0, 1) * at(1, 0) * at(2, 2) - at(0, 2) * at(1, 1) * at(2, 0);
     }
fromColumnMajorArray()
template<class T> template<class FromT > static Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::fromColumnMajorArray (const FromT * arr) inline static
Creates new matrix 3x3 from array that represents such matrix 3x3 as array of tightly packed elements in column major order.
Parameters
arr An array of elements for 3x3 matrix in column major order.
Returns
An instance of Matrix3<T> representing arr
Definition at line 1961 of file vmath.h.
     {
         const T retData[] =
         { static_cast<T>(arr[0]), static_cast<T>(arr[1]), static_cast<T>(arr[2]), static_cast<T>(arr[3]),
                 static_cast<T>(arr[4]), static_cast<T>(arr[5]), static_cast<T>(arr[6]), static_cast<T>(arr[7]),
                 static_cast<T>(arr[8]) };
         return retData;
     }
fromOde()
template<class T> template<class It > static Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::fromOde (const It * mat) inline static
Creates rotation matrix from ODE Matrix.
Definition at line 1924 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::at().
     {
         Matrix3<T> ret;
         for (int i = 0; i < 3; i++)
         {
             for (int j = 0; j < 3; j++)
             {
                 ret.at(i, j) = static_cast<T>(mat[j * 4 + i]);
             }
         }
         return ret;
     }
fromRowMajorArray()
template<class T> template<class FromT > static Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::fromRowMajorArray (const FromT * arr) inline static
Creates new matrix 3x3 from array that represents such matrix 3x3 as array of tightly packed elements in row major order.
Parameters
arr An array of elements for 3x3 matrix in row major order.
Returns
An instance of Matrix3<T> representing arr
Definition at line 1944 of file vmath.h.
     {
         const T retData[] =
         { static_cast<T>(arr[0]), static_cast<T>(arr[3]), static_cast<T>(arr[6]), static_cast<T>(arr[1]),
                 static_cast<T>(arr[4]), static_cast<T>(arr[7]), static_cast<T>(arr[2]), static_cast<T>(arr[5]),
                 static_cast<T>(arr[8]) };
         return retData;
     }
getEulerAngles()
template<class T> static Vector3<T> VMATH_NAMESPACE::Matrix3< T >::getEulerAngles (Matrix3< T > R) inline static
Definition at line 1887 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::at(), VMATH_NAMESPACE::closeEnough(), M_PI, VMATH_NAMESPACE::Vector2< T >::x, and VMATH_NAMESPACE::Vector2< T >::y.
{
         //check for gimbal lock
         if (closeEnough(R.at(2,0), -1.0f)) {
             float x = 0; //gimbal lock, value of x doesn't matter
             float y = M_PI / 2;
             float z = x + atan2(R.at(0,1), R.at(0,2));
             return Vector3<T>(x, y, z);
         } else if (closeEnough(R.at(2,0), 1.0f)) {
             float x = 0;
             float y = -M_PI / 2;
             float z = -x + atan2(-R.at(0,1), -R.at(0,2));
             return Vector3<T>(x, y, z);
         } else { //two solutions exist
             float x1 = -asin(R.at(2,0));
             float x2 = M_PI - x1;
             float y1 = atan2(R.at(2,1) / cos(x1), R.at(2,2) / cos(x1));
             float y2 = atan2(R.at(2,1) / cos(x2), R.at(2,2) / cos(x2));
             float z1 = atan2(R.at(1,0) / cos(x1), R.at(0,0) / cos(x1));
             float z2 = atan2(R.at(1,0) / cos(x2), R.at(0,0) / cos(x2));
             //choose one solution to return
             //for example the "shortest" rotation
             if ((std::abs(x1) + std::abs(y1) + std::abs(z1)) <= (std::abs(x2) + std::abs(y2) + std::abs(z2))) {
                 return Vector3<T>(x1, y1, z1);
             } else {
                 return Vector3<T>(x2, y2, z2);
             }
         }
     }
identity()
template<class T> void VMATH_NAMESPACE::Matrix3< T >::identity () inline
Resets matrix to be identity matrix
Definition at line 1808 of file vmath.h.
     {
         for (int i = 0; i < 9; i++)
             data[i] = (i % 4) ? 0 : 1;
     }
inverse()
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::inverse () inline
Computes inverse matrix
Returns
Inverse matrix of this matrix.
Definition at line 2238 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::at().
     {
         Matrix3<T> ret;
         ret.at(0, 0) = at(1, 1) * at(2, 2) - at(2, 1) * at(1, 2);
         ret.at(0, 1) = at(2, 1) * at(0, 2) - at(0, 1) * at(2, 2);
         ret.at(0, 2) = at(0, 1) * at(1, 2) - at(1, 1) * at(0, 2);
         ret.at(1, 0) = at(2, 0) * at(1, 2) - at(1, 0) * at(2, 2);
         ret.at(1, 1) = at(0, 0) * at(2, 2) - at(2, 0) * at(0, 2);
         ret.at(1, 2) = at(1, 0) * at(0, 2) - at(0, 0) * at(1, 2);
         ret.at(2, 0) = at(1, 0) * at(2, 1) - at(2, 0) * at(1, 1);
         ret.at(2, 1) = at(2, 0) * at(0, 1) - at(0, 0) * at(2, 1);
         ret.at(2, 2) = at(0, 0) * at(1, 1) - at(1, 0) * at(0, 1);
         return ret * (1.0f / det());
     }
lerp()
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::lerp (T fact, const Matrix3< T > & rhs) const inline
Linear interpolation of two matrices
Parameters
fact Factor of interpolation. For translation from positon of this matrix (lhs) to matrix rhs, values of factor goes from 0.0 to 1.0.
rhs Second Matrix for interpolation
Note
However values of fact parameter are reasonable only in interval [0.0 , 1.0], you can pass also values outside of this interval and you can get result (extrapolation?)
Definition at line 2222 of file vmath.h.
     {
         Matrix3<T> ret = (*this) + (rhs - (*this)) * fact;
         return ret;
     }
operator const T *()
template<class T> VMATH_NAMESPACE::Matrix3< T >::operator const T * () const inline
Conversion to pointer operator
Returns
Constant Pointer to internally stored (in management of class Matrix3<T>) used for passing Matrix3<T> values to gl*[fd]v functions.
Definition at line 2270 of file vmath.h.
     {
         return (const T*) data;
     }
operator T*()
template<class T> VMATH_NAMESPACE::Matrix3< T >::operator T* () inline
Conversion to pointer operator
Returns
Pointer to internally stored (in management of class Matrix3<T>) used for passing Matrix3<T> values to gl*[fd]v functions.
Definition at line 2260 of file vmath.h.
     {
         return (T*) data;
     }
operator!=()
template<class T> bool VMATH_NAMESPACE::Matrix3< T >::operator!= (const Matrix3< T > & rhs) const inline
Inequality test operator
Parameters
rhs Right hand side argument of binary operator.
Returns
not (lhs == rhs) :-P
Definition at line 1995 of file vmath.h.
     {
         return !(*this == rhs);
     }
operator()() [1/2]
template<class T> T& VMATH_NAMESPACE::Matrix3< T >::operator() (int i, int j) inline
Get reference to element at position (i,j), with math matrix notation
Parameters
i Number of row (1..3)
j Number of column (1..3)
Definition at line 2030 of file vmath.h.
     {
         assert(i >= 1 && i <= 3);
         assert(j >= 1 && j <= 3);
         return data[(j - 1) * 3 + i - 1];
     }
operator()() [2/2]
template<class T> const T& VMATH_NAMESPACE::Matrix3< T >::operator() (int i, int j) const inline
Get constant reference to element at position (i,j), with math matrix notation
Parameters
i Number of row (1..3)
j Number of column (1..3)
Definition at line 2042 of file vmath.h.
     {
         assert(i >= 1 && i <= 3);
         assert(j >= 1 && j <= 3);
         return data[(j - 1) * 3 + i - 1];
     }
operator*() [1/3]
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::operator* (T rhs) const inline
Multiplication operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2143 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         Matrix3<T> ret;
         for (int i = 0; i < 9; i++)
             ret.data[i] = data[i] * rhs;
         return ret;
     }
operator*() [2/3]
template<class T> Vector3<T> VMATH_NAMESPACE::Matrix3< T >::operator* (const Vector3< T > & rhs) const inline
Multiplication operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2168 of file vmath.h.
References VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
     {
         return Vector3<T>(data[0] * rhs.x + data[3] * rhs.y + data[6] * rhs.z,
                 data[1] * rhs.x + data[4] * rhs.y + data[7] * rhs.z,
                 data[2] * rhs.x + data[5] * rhs.y + data[8] * rhs.z);
     }
operator*() [3/3]
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::operator* (Matrix3< T > rhs) const inline
Multiplication operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2179 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::at().
     {
         static Matrix3<T> w;
         for (int i = 0; i < 3; i++)
         {
             for (int j = 0; j < 3; j++)
             {
                 T n = 0;
                 for (int k = 0; k < 3; k++)
                     n += rhs.at(i, k) * at(k, j);
                 w.at(i, j) = n;
             }
         }
         return w;
     }
operator+() [1/2]
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::operator+ (const Matrix3< T > & rhs) const inline
Addition operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2094 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         Matrix3<T> ret;
         for (int i = 0; i < 9; i++)
             ret.data[i] = data[i] + rhs.data[i];
         return ret;
     }
operator+() [2/2]
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::operator+ (T rhs) const inline
Addition operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2119 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         Matrix3<T> ret;
         for (int i = 0; i < 9; i++)
             ret.data[i] = data[i] + rhs;
         return ret;
     }
operator-() [1/2]
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::operator- (const Matrix3< T > & rhs) const inline
Subtraction operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2106 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         Matrix3<T> ret;
         for (int i = 0; i < 9; i++)
             ret.data[i] = data[i] - rhs.data[i];
         return ret;
     }
operator-() [2/2]
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::operator- (T rhs) const inline
Subtraction operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2131 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         Matrix3<T> ret;
         for (int i = 0; i < 9; i++)
             ret.data[i] = data[i] - rhs;
         return ret;
     }
operator/()
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::operator/ (T rhs) const inline
Division operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2155 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         Matrix3<T> ret;
         for (int i = 0; i < 9; i++)
             ret.data[i] = data[i] / rhs;
         return ret;
     }
operator=() [1/3]
template<class T> Matrix3<T>& VMATH_NAMESPACE::Matrix3< T >::operator= (const Matrix3< T > & rhs) inline
Copy operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2053 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         std::memcpy(data, rhs.data, sizeof(T) * 9);
         return *this;
     }
operator=() [2/3]
template<class T> template<class FromT > Matrix3<T>& VMATH_NAMESPACE::Matrix3< T >::operator= (const Matrix3< FromT > & rhs) inline
Copy casting operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2064 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data.
     {
         for (int i = 0; i < 9; i++)
         {
             data[i] = static_cast<T>(rhs.data[i]);
         }
         return *this;
     }
operator=() [3/3]
template<class T> Matrix3<T>& VMATH_NAMESPACE::Matrix3< T >::operator= (const T * rhs) inline
Copy operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 2077 of file vmath.h.
     {
         std::memcpy(data, rhs, sizeof(T) * 9);
         return *this;
     }
operator==()
template<class T> bool VMATH_NAMESPACE::Matrix3< T >::operator== (const Matrix3< T > & rhs) const inline
Equality test operator
Parameters
rhs Right hand side argument of binary operator.
Note
Test of equality is based of threshold EPSILON value. To be two values equal, must satisfy this condition all elements of matrix | lhs[i] - rhs[i] | < EPSILON, same for y-coordinate, z-coordinate, and w-coordinate.
Definition at line 1980 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::data, and EPSILON.
     {
         for (int i = 0; i < 9; i++)
         {
             if (std::fabs(data[i] - rhs.data[i]) >= EPSILON)
                 return false;
         }
         return true;
     }
toString()
template<class T> std::string VMATH_NAMESPACE::Matrix3< T >::toString () const inline
Gets string representation.
Definition at line 2299 of file vmath.h.
     {
         std::ostringstream oss;
         oss << *this;
         return oss.str();
     }
transpose()
template<class T> Matrix3<T> VMATH_NAMESPACE::Matrix3< T >::transpose () inline
Transpose matrix.
Definition at line 2200 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::at().
     {
         Matrix3<T> ret;
         for (int i = 0; i < 3; i++)
         {
             for (int j = 0; j < 3; j++)
             {
                 ret.at(i, j) = at(j, i);
             }
         }
         return ret;
     }
vectorProductMatrix() [1/2]
template<class T> Vector3<T> VMATH_NAMESPACE::Matrix3< T >::vectorProductMatrix (const Vector3< T > & v) const inline
vectorProductMatrix: Multiplication function
Parameters
v vector3
Returns
v multiplied by currentMatrix (Matrix3)
Definition at line 1819 of file vmath.h.
     {
         Vector3<T> vxm;
         for(int i = 0; i < 3; i++){
             for(int j = 0; j < 3; j++){
                 vxm[i] += at(i,j) * v[j];
             }
         }
         return vxm;
     }
vectorProductMatrix() [2/2]
template<class T> static Vector3<T> VMATH_NAMESPACE::Matrix3< T >::vectorProductMatrix (const Vector3< T > v, Matrix3< T > m) inline static
vectorProductMatrix: Multiplication function
Parameters
v row vector3
m Matrix3
Returns
Vector3: v * m
Definition at line 1836 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::at().
     {
         Vector3<T> vxm;
         for(int i = 0; i < 3; i++){
             for(int j = 0; j < 3; j++){
                 vxm[i] += m.at(i,j) * v[j];
             }
         }
         return vxm;
     }
Friends And Related Function Documentation
operator<<
template<class T> std::ostream& operator<< (std::ostream & lhs, const Matrix3< T > & rhs) friend
Output to stream operator
Parameters
lhs Left hand side argument of operator (commonly ostream instance).
rhs Right hand side argument of operator.
Returns
Left hand side argument - the ostream object passed to operator.
Definition at line 2282 of file vmath.h.
     {
         for (int i = 0; i < 3; i++)
         {
             lhs << "|\t";
             for (int j = 0; j < 3; j++)
             {
                 lhs << rhs.at(j, i) << "\t";
             }
             lhs << "|" << std::endl;
         }
         return lhs;
     }
Member Data Documentation
data
template<class T> T VMATH_NAMESPACE::Matrix3< T >::data[9]
Data stored in column major order.
Definition at line 1762 of file vmath.h.
Referenced by VMATH_NAMESPACE::Matrix3< T >::Matrix3(), VMATH_NAMESPACE::Matrix3< T >::operator*(), VMATH_NAMESPACE::Matrix3< T >::operator+(), VMATH_NAMESPACE::Matrix3< T >::operator-(), VMATH_NAMESPACE::Matrix3< T >::operator/(), VMATH_NAMESPACE::Matrix3< T >::operator=(), and VMATH_NAMESPACE::Matrix3< T >::operator==().
The documentation for this class was generated from the following file:
C:/vmtk_Multi-volume_Raycasting/include/vmath.h