VMTK: VMATH_NAMESPACE::Aabb3< T > Class Template Reference
VMATH_NAMESPACE::Aabb3< T > Class Template Reference
#include <vmath.h>
Public Member Functions
Aabb3 ()
template<typename SrcT >
Aabb3 (const Vector3< SrcT > &point)
template<typename SrcT >
Aabb3 (SrcT x0, SrcT y0, SrcT z0, SrcT x1, SrcT y1, SrcT z1)
template<typename SrcT >
Aabb3 (SrcT x, SrcT y, SrcT z)
template<typename SrcT >
Aabb3 (const Aabb3< SrcT > &src)
template<typename SrcT >
Aabb3< T > & operator= (const Aabb3< SrcT > &rhs)
bool valid () const
void invalidate ()
template<typename SrcT >
void extend (const Vector3< SrcT > &point)
template<typename SrcT >
void extend (const Aabb3< SrcT > &box)
template<typename SrcT >
Aabb3< T > extended (const Vector3< SrcT > &point) const
template<typename SrcT >
Aabb3< T > extended (const Aabb3< SrcT > &box) const
template<typename SrcT >
bool intersects (const Vector3< SrcT > &point) const
template<typename SrcT >
bool intersects (const Aabb3< SrcT > &box) const
template<typename SrcT >
Aabb3< T > intersection (const Aabb3< SrcT > &other) const
Vector3< T > center () const
Vector3< T > extent () const
Vector3< T > size () const
Vector3< T > point (size_t i) const
Aabb3< T > transformed (const Matrix4< T > &t) const
template<typename RhsT >
bool operator== (const Aabb3< RhsT > &rhs) const
template<typename RhsT >
bool operator!= (const Aabb3< RhsT > &rhs) const
Aabb3< T > operator* (const Matrix4< T > &rhs) const
Aabb3< T > & operator*= (const Matrix4< T > &rhs)
template<typename SrcT >
Aabb3< T > & operator<< (const Vector3< SrcT > &rhs)
template<typename SrcT >
Aabb3< T > & operator<< (const Aabb3< SrcT > &rhs)
template<typename RhsT >
Aabb3< T > operator| (const Aabb3< RhsT > &rhs) const
template<typename RhsT >
Aabb3< T > operator & (const Aabb3< RhsT > &rhs) const
Public Attributes
Vector3< T > min
Vector3< T > max
Friends
std::ostream & operator<< (std::ostream &lhs, const Aabb3< T > &rhs)
Detailed Description
template<typename T>
class VMATH_NAMESPACE::Aabb3< T >
Axes-aligned bounding-box (aka AABB) class.
This class provides functionality for:
creating AABB from point, or other AABB,
testing if point of other AABB intersects with,
getting result of intersection with other AABB,
transforming AABB with 4x4 matrix.
There are also overloaded couple of operators to shorten common operation. For instance you can use operator<< on AABB to extend it with passed point or other AABB.
Aabb3f aabb;
aabb << Vector3f(1, 1, 2) << Aabb3f(-3,-3,-3, 2, 2, 2);
Definition at line 4022 of file vmath.h.
Constructor & Destructor Documentation
Aabb3() [1/5]
template<typename T> VMATH_NAMESPACE::Aabb3< T >::Aabb3 () inline
Constructs invalid axes-aligned bounding-box.
See also
valid() for explanation of invalid bounding-box usage.
Definition at line 4039 of file vmath.h.
             : min(1,1,1), max(-1,-1,-1)
         {}
Aabb3() [2/5]
template<typename T> template<typename SrcT > VMATH_NAMESPACE::Aabb3< T >::Aabb3 (const Vector3< SrcT > & point) inline
Constructs axes-aligned bound-box containing one point point
Parameters
point
Definition at line 4048 of file vmath.h.
             : min(point), max(point)
         {}
Aabb3() [3/5]
template<typename T> template<typename SrcT > VMATH_NAMESPACE::Aabb3< T >::Aabb3 (SrcT x0, SrcT y0, SrcT z0, SrcT x1, SrcT y1, SrcT z1) inline
Constructs axes-aligned bounding-box form two corner points (x0, y0, z0) and (x1, y1, z1)
Parameters
x0 X-coordinate of first point
y0 Y-coordinate of first point
z0 Z-coordinate of first point
x1 X-coordinate of second point
y1 Y-coordinate of second point
z1 Z-coordinate of second point
Definition at line 4063 of file vmath.h.
             : min(std::min(x0,x1), std::min(y0,y1), std::min(z0,z1)),
               max(std::max(x0,x1), std::max(y0,y1), std::max(z0,z1))
         {}
Aabb3() [4/5]
template<typename T> template<typename SrcT > VMATH_NAMESPACE::Aabb3< T >::Aabb3 (SrcT x, SrcT y, SrcT z) inline
Constructs axes-aligned bounding-box containing point (x, y, z)
Parameters
x X-coordinate of point
y Y-coordinate of point
z Z-coordinate of point
Definition at line 4075 of file vmath.h.
             : min(x,y,z), max(x,y,z)
         {}
Aabb3() [5/5]
template<typename T> template<typename SrcT > VMATH_NAMESPACE::Aabb3< T >::Aabb3 (const Aabb3< SrcT > & src) inline
Creates copy of axis-aligned bounding-box
Parameters
src Source bounding-box
Definition at line 4084 of file vmath.h.
             : min(src.min), max(src.max)
         {}
Member Function Documentation
center()
template<typename T> Vector3<T> VMATH_NAMESPACE::Aabb3< T >::center () const inline
Gets center point of bounding-box.
Returns
A center point of bounding-box.
Definition at line 4261 of file vmath.h.
         { return (min + max) * 0.5f; }
extend() [1/2]
template<typename T> template<typename SrcT > void VMATH_NAMESPACE::Aabb3< T >::extend (const Vector3< SrcT > & point) inline
Extends this bounding-box by a point point.
Parameters
point A point to extend bounding-box by.
Definition at line 4123 of file vmath.h.
References std::max(), and std::min().
Referenced by VMATH_NAMESPACE::Aabb3< T >::extended(), and VMATH_NAMESPACE::Aabb3< T >::transformed().
         {
             if (!valid())
             {
                 min = max = point;
             }
             else
             {
                 min = std::min(min, point);
                 max = std::max(max, point);
             }
         }
extend() [2/2]
template<typename T> template<typename SrcT > void VMATH_NAMESPACE::Aabb3< T >::extend (const Aabb3< SrcT > & box) inline
Extends this bounding-box by a box box.
Parameters
box A box to extend this bounding-box by.
Definition at line 4141 of file vmath.h.
References std::max(), VMATH_NAMESPACE::Aabb3< T >::max, std::min(), and VMATH_NAMESPACE::Aabb3< T >::min.
         {
             if (!valid())
             {
                 min = box.min;
                 max = box.max;
             }
             else
             {
                 min = std::min(min, box.min);
                 max = std::max(max, box.max);
             }
         }
extended() [1/2]
template<typename T> template<typename SrcT > Aabb3<T> VMATH_NAMESPACE::Aabb3< T >::extended (const Vector3< SrcT > & point) const inline
Gets a copy of this bounding-box extend by a point point.
Parameters
point A point to extend the box by
Returns
Copy of extended bounding-box
Definition at line 4161 of file vmath.h.
References VMATH_NAMESPACE::Aabb3< T >::extend().
         {
             Aabb3<T> ret(*this);
             ret.extend(point);
             return ret;
         }
extended() [2/2]
template<typename T> template<typename SrcT > Aabb3<T> VMATH_NAMESPACE::Aabb3< T >::extended (const Aabb3< SrcT > & box) const inline
Gets a copy of this bounding-box extnended by box box.
Parameters
box A box to extend the copy be.
Returns
Copy of extended bounding-box
Definition at line 4174 of file vmath.h.
References VMATH_NAMESPACE::Aabb3< T >::extend().
         {
             Aabb3<T> ret(*this);
             ret.extend(box);
             return ret;
         }
extent()
template<typename T> Vector3<T> VMATH_NAMESPACE::Aabb3< T >::extent () const inline
Gets extent of bounding-box.
Returns
Extent of bounding-box.
Definition at line 4268 of file vmath.h.
         { return (max - min) * 0.5f; }
intersection()
template<typename T> template<typename SrcT > Aabb3<T> VMATH_NAMESPACE::Aabb3< T >::intersection (const Aabb3< SrcT > & other) const inline
Gets result of intersection of this bounding-box with other bounding-box. In case the boxes don't intersect, the returned bounding-box is invalid.
Parameters
other Box to be tested
Returns
Result of intersection.
See also
valid() method for more information on invalid bounding-boxes.
Definition at line 4241 of file vmath.h.
References std::max(), VMATH_NAMESPACE::Aabb3< T >::max, std::min(), VMATH_NAMESPACE::Aabb3< T >::min, VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
         {
             Aabb3<T> ret;
             if (max.x < other.min.x || min.x > other.max.x)
                 return ret;
             if (max.y < other.min.y || min.y > other.max.y)
                 return ret;
             if (max.z < other.min.z || min.z > other.max.z)
                 return ret;
             ret.min = std::max(min, other.min);
             ret.max = std::min(max, other.max);
             return ret;
         }
intersects() [1/2]
template<typename T> template<typename SrcT > bool VMATH_NAMESPACE::Aabb3< T >::intersects (const Vector3< SrcT > & point) const inline
Tests if the point point is within this bounding-box
Parameters
point A point to be tested
Returns
True if point point lies within bounding-box, otherwise false.
Definition at line 4187 of file vmath.h.
References VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
         {
             /*
             for (size_t i = 0; i < 3; i++)
             {
                 if (min[i] > point[i] || point[i] > max[i])
                     return false;
             }
             */
             // unrolled loop above
             if (min.x > point.x || point.x > max.x)
                 return false;
             if (min.y > point.y || point.y > max.y)
                 return false;
             if (min.z > point.z || point.z > max.z)
                 return false;
             return true;
         }
intersects() [2/2]
template<typename T> template<typename SrcT > bool VMATH_NAMESPACE::Aabb3< T >::intersects (const Aabb3< SrcT > & box) const inline
Tests if other bounding-box box intersects (even partially) with this bouding-box.
Parameters
box A box to be tested for intersection.
Returns
True if there's intersection between boxes, otherwise false.
Definition at line 4213 of file vmath.h.
References VMATH_NAMESPACE::Aabb3< T >::max, VMATH_NAMESPACE::Aabb3< T >::min, VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
         {
             /*
             for (size_t i = 0; i < 3; i++)
             {
                 if (max[i] < box.min[i] || min[i] > box.max[i])
                     return false;
             }
             */
             // unrolled loop above
             if (max.x < box.min.x || min.x > box.max.x)
                 return false;
             if (max.y < box.min.y || min.y > box.max.y)
                 return false;
             if (max.z < box.min.z || min.z > box.max.z)
                 return false;
             return true;
         }
invalidate()
template<typename T> void VMATH_NAMESPACE::Aabb3< T >::invalidate () inline
Makes this bounding-box invalid. So calling valid() gets false.
See also
valid() method for more info on usage of invalid bounding-boxes.
Definition at line 4115 of file vmath.h.
         { min = Vector3<T>(1,1,1); max = Vector3<T>(-1,-1,-1); }
operator &()
template<typename T> template<typename RhsT > Aabb3<T> VMATH_NAMESPACE::Aabb3< T >::operator& (const Aabb3< RhsT > & rhs) const inline
Intersection of this and rhs bounding-boxed
Parameters
rhs Right-hand side
Returns
Resulting bouding-box representing the intersection.
Definition at line 4404 of file vmath.h.
         {
             return intersection(rhs);
         }
operator!=()
template<typename T> template<typename RhsT > bool VMATH_NAMESPACE::Aabb3< T >::operator!= (const Aabb3< RhsT > & rhs) const inline
Tests if rhs is not equal to this bounding-box
Parameters
rhs Right-hand side
Returns
True if rhs and this bounding-boxes are not equal, otherwise false
Definition at line 4336 of file vmath.h.
References VMATH_NAMESPACE::Aabb3< T >::max, and VMATH_NAMESPACE::Aabb3< T >::min.
         {
             return min != rhs.min || max != rhs.max;
         }
operator*()
template<typename T> Aabb3<T> VMATH_NAMESPACE::Aabb3< T >::operator* (const Matrix4< T > & rhs) const inline
Gets transformed bounding-box by transform rhs.
Parameters
rhs Matrix 4x4 representing the transform
Returns
Transformed bounding-box
Definition at line 4346 of file vmath.h.
         {
             return transformed(rhs);
         }
operator*=()
template<typename T> Aabb3<T>& VMATH_NAMESPACE::Aabb3< T >::operator*= (const Matrix4< T > & rhs) inline
Apply transform rhs to this bounding-box
Parameters
rhs A transform to be applied
Returns
Reference to this
Definition at line 4356 of file vmath.h.
         {
             *this = transformed(rhs);
             return *this;
         }
operator<<() [1/2]
template<typename T> template<typename SrcT > Aabb3<T>& VMATH_NAMESPACE::Aabb3< T >::operator<< (const Vector3< SrcT > & rhs) inline
Extends this bounding-box by point rhs.
Parameters
rhs A point to extend this bounding-box by
Returns
Reference to this
Definition at line 4369 of file vmath.h.
         {
             extend(rhs);
             return *this;
         }
operator<<() [2/2]
template<typename T> template<typename SrcT > Aabb3<T>& VMATH_NAMESPACE::Aabb3< T >::operator<< (const Aabb3< SrcT > & rhs) inline
Extends this bounding-box by box rhs.
Parameters
rhs A box to extend this bounding-box by
Returns
Reference to this
Definition at line 4381 of file vmath.h.
         {
             extend(rhs);
             return *this;
         }
operator=()
template<typename T> template<typename SrcT > Aabb3<T>& VMATH_NAMESPACE::Aabb3< T >::operator= (const Aabb3< SrcT > & rhs) inline
Assign operator
Parameters
rhs source bounding-box
Returns
refenrence to this
Definition at line 4094 of file vmath.h.
References VMATH_NAMESPACE::Aabb3< T >::max, and VMATH_NAMESPACE::Aabb3< T >::min.
         {
             min = rhs.min;
             max = rhs.max;
             return *this;
         }
operator==()
template<typename T> template<typename RhsT > bool VMATH_NAMESPACE::Aabb3< T >::operator== (const Aabb3< RhsT > & rhs) const inline
Tests if rhs is equal to this bounding-box
Parameters
rhs Right-hand side
Returns
True if rhs and this bounding-boxes are equal, otherwise false
Definition at line 4325 of file vmath.h.
References VMATH_NAMESPACE::Aabb3< T >::max, and VMATH_NAMESPACE::Aabb3< T >::min.
         {
             return min == rhs.min && max == rhs.max;
         }
operator|()
template<typename T> template<typename RhsT > Aabb3<T> VMATH_NAMESPACE::Aabb3< T >::operator| (const Aabb3< RhsT > & rhs) const inline
Union of this and rhs bounding-boxes
Parameters
rhs Right-hand side of union
Returns
A resulting bounding-box representing union
Definition at line 4393 of file vmath.h.
         {
             return extended(rhs);
         }
point()
template<typename T> Vector3<T> VMATH_NAMESPACE::Aabb3< T >::point (size_t i) const inline
Gets all 8 corner-points of bounding box
Parameters
i An index of bounding-box corner point. Valid values are 0 .. 7.
Returns
A position of i-th corner-point.
Note
The order of points is as follows (where + denotes max-point and - min-point):
(+ + +)
(- + +)
(+ - +)
(- - +)
(+ + -)
(- + -)
(+ - -)
(- - -)
Definition at line 4293 of file vmath.h.
References VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
         {
             assert(i < 8);
             return Vector3<T>(i & 1 ? min.x : max.x, i & 2 ? min.y : max.y, i & 4 ? min.z : max.z);
         }
size()
template<typename T> Vector3<T> VMATH_NAMESPACE::Aabb3< T >::size () const inline
Gets diagonal size of bounding-box
Returns
Sizes for particular dimensions.
Definition at line 4275 of file vmath.h.
References std::min().
         { return max - min; }
transformed()
template<typename T> Aabb3<T> VMATH_NAMESPACE::Aabb3< T >::transformed (const Matrix4< T > & t) const inline
Gets transformed bounding-box by transform t
Parameters
t A transform matrix
Returns
Transformed bounding-box
Definition at line 4304 of file vmath.h.
References VMATH_NAMESPACE::Aabb3< T >::extend().
         {
             Aabb3<T> ret;
             for (size_t i = 0; i < 8; i++)
             {
                 const Vector4<T> p(point(i), 1);
                 ret.extend((t * p).xyz());
             }
             return ret;
         }
valid()
template<typename T> bool VMATH_NAMESPACE::Aabb3< T >::valid () const inline
Checks if bounding-box is valid. Valid bounding-box has non-negative size. If an invalid bounding-box is extended by point or another bounding-box, the target bounding box becomes valid and contains solely the source point or bounding-box respectively.
Returns
True if box is valid, otherwise false
Definition at line 4108 of file vmath.h.
References VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
         { return min.x <= max.x && min.y <= max.y && min.z <= max.z; }
Friends And Related Function Documentation
operator<<
template<typename T> std::ostream& operator<< (std::ostream & lhs, const Aabb3< T > & rhs) friend
Outputs string representation of bounding-box rhs to output stream lhs
Parameters
lhs Output stream to write to
rhs Bounding-box to write to output stream.
Returns
Reference to output stream lhs
Definition at line 4415 of file vmath.h.
         {
             lhs << rhs.min << " x " << rhs.max;
             return lhs;
         }
Member Data Documentation
max
template<typename T> Vector3<T> VMATH_NAMESPACE::Aabb3< T >::max
Position of Max corner of bounding box
Definition at line 4033 of file vmath.h.
Referenced by VMATH_NAMESPACE::Aabb3< T >::extend(), VMATH_NAMESPACE::Aabb3< T >::intersection(), VMATH_NAMESPACE::Aabb3< T >::intersects(), VMATH_NAMESPACE::Aabb3< T >::operator!=(), VMATH_NAMESPACE::Aabb3< T >::operator=(), and VMATH_NAMESPACE::Aabb3< T >::operator==().
min
template<typename T> Vector3<T> VMATH_NAMESPACE::Aabb3< T >::min
Position of Min corner of bounding box.
Definition at line 4028 of file vmath.h.
Referenced by VMATH_NAMESPACE::Aabb3< T >::extend(), VMATH_NAMESPACE::Aabb3< T >::intersection(), VMATH_NAMESPACE::Aabb3< T >::intersects(), VMATH_NAMESPACE::Aabb3< T >::operator!=(), VMATH_NAMESPACE::Aabb3< T >::operator=(), and VMATH_NAMESPACE::Aabb3< T >::operator==().
The documentation for this class was generated from the following file:
C:/vmtk_Multi-volume_Raycasting/include/vmath.h