VMTK: vmtkRender3D Class Reference
vmtkRender3D Class Reference
#include <vmtkRender3D.h>
Classes
struct VertexData
struct VertexDataCube
Public Member Functions
vmtkRender3D ()
vmtkRenderer3D constructor
void setAcquisition (std::vector< Import::ImgFormat *> acqVector)
sets the volumes to be registered.
Import::ImgFormat * getAcquisition (int id)
get acquisition of the volumes.
void initialize (int width, int height)
initializes 3D volume rendering.
void render ()
renders the data with the specified redering mode.
void preRender (vmath::Matrix4f mvp)
renders the color cube in the fbos.
void resize (int width, int height)
resizes the dimensions of the display.
void setRotation (float ax, float ay, float az)
sets the rotation matrix.
void setThreshold (int threshold)
sets the threshold.
void setBlender (float blender)
sets the blender factor.
void itlDrawColorCube (vmath::Matrix4f mvp)
draws a unit cube to get the front and the back depth maps of the volume cube, after updating the clipping plane values.
void initDrawCube ()
initializes the geometry of a cube to be rendered for getting back and front depth maps.
bool readMatrix (const char *s, vmath::Matrix4f &invRM)
reads the co-register matrix.
bool readPlane (const char *s, vmath::Vector4f &eqp)
readPlane
void setClipLeftX (float left_x)
sets the clipping plane.
int getMaxSliceLeft ()
gets the maximum number of the slices from the axis X.
void volumeRealDimension (Import::ImgFormat *data, float vrd[])
volumeRealDimension
float maximumDimension (float vrd[])
maximumDimension
vmath::Vector4f scaleFactors (float vrd[], float maxDim)
scaleFactors
vmath::Vector4f phyDimension (Import::ImgFormat *data)
phyDimension
int currentActivateTexture ()
currentActivateTexture
void mapEqualizeHistogramVolume (Import::ImgFormat *data, unsigned short *&map)
mapEqualizeHistogramVolume
void volumeEqualizer (Import::ImgFormat *data, unsigned short *map, unsigned short *&texbuffer)
volumeEqualizer
void texture3DFromVolume (Import::ImgFormat *data, unsigned short *texbuffer, GLuint &idTexture)
texture3DFromVolume
void generateTransferFunction (Import::ImgFormat *data, int &dim, unsigned char *&tf)
generateTransferFunction
void texture1DFromTransferFunction (int dim, unsigned char *tf, GLuint &idTF)
texture1DFromTransferFunction
void setMPR (vmath::Vector4f eqp)
setMPR
void setEnableMPR (bool enableMPR)
setEnableMPR
void setStateMPRInput (bool stateMPRInput)
setStateMPRInput
void setVectorInvMatrixReg (std::vector< vmath::Matrix4f > imr)
setVectorInvMatrixReg
Private Member Functions
void createVectorPlanes ()
defines the position and texture coordinates of the four vertices of a plane.
void loadVolumesToTextures ()
loads volumes to textures 3D.
void loadTransferFunctionsToTexture ()
Loads transfer Functions to textures 1D.
void createBuffers ()
creates vertex arrays and their buffer data.
void initRenderPlane ()
initializes the plane to be input into the graphics pipeline
void drawCube ()
draws a cube.
void raycastingMultiVolume ()
raycasts through the color cube.
void drawPlaneRayTraced ()
draws the plane from pre-render shader.
Private Attributes
int m_maxSliceLeft
float m_blender
vmath::Matrix4f * m_invRegMatrix
std::vector< unsigned short * > m_map
std::vector< float > m_Threshold
std::vector< Import::ImgFormat * > m_data
std::vector< GLuint > m_idTexture
std::vector< GLuint > m_idTF
vmath::Vector4f m_equationPlaneForMPR
bool m_enableMPR
bool m_stateMPRInput
GLuint m_ColorShader
GLuint m_RaytraceShader
GLuint vaosCube
GLuint vboCube
GLuint eboCube
GLuint vaosRenderPlane
GLuint vboRenderPlane
GLuint eboRenderPlane
GLuint vaosResultPlane
GLuint vboResultPlane
GLuint eboResultPlane
vmath::Vector2f v1
Position vectors of VertexData.
vmath::Vector2f v2
vmath::Vector2f v3
vmath::Vector2f v4
vmath::Vector2f vt1
Texture vectors of VertexData.
vmath::Vector2f vt2
vmath::Vector2f vt3
vmath::Vector2f vt4
vmath::Vector3f vc1
Position vectors of VertexDataCube.
vmath::Vector3f vc2
vmath::Vector3f vc3
vmath::Vector3f vc4
vmath::Vector3f vc5
vmath::Vector3f vc6
vmath::Vector3f vc7
vmath::Vector3f vc8
vmath::Vector3f vc9
vmath::Vector3f vc10
vmath::Vector3f vc11
vmath::Vector3f vc12
vmath::Vector3f vc13
vmath::Vector3f vc14
vmath::Vector3f vc15
vmath::Vector3f vc16
vmath::Vector3f vc17
vmath::Vector3f vc18
vmath::Vector3f vc19
vmath::Vector3f vc20
vmath::Vector3f vc21
vmath::Vector3f vc22
vmath::Vector3f vc23
vmath::Vector3f vc24
float m_fClipXLeft
float m_fClipXRight
float m_fClipYTop
float m_fClipYBottom
float m_fClipZBack
float m_fClipZFront
int m_iHeight
int m_iWidth
vmath::Matrix4f m_projectionMatrix
vmath::Matrix4f m_modelViewMatrix
vmath::Matrix4f m_rotationMatrix
vmath::Matrix4f m_scalationMatrix
vmath::Matrix4f m_translationMatrix
vmath::Vector4f * m_phyDimensions
vmath::Vector4f * m_scaleFactors
vmtkFrameBufferObject * m_FrontFBO
vmtkFrameBufferObject * m_BackFBO
vmtkFrameBufferObject * m_RayTracedFBO
bool m_bInitialized
Detailed Description
Definition at line 24 of file vmtkRender3D.h.
Constructor & Destructor Documentation
vmtkRender3D()
vmtkRender3D::vmtkRender3D ()
vmtkRenderer3D constructor
Definition at line 5 of file vmtkRender3D.cpp.
References m_bInitialized, m_blender, m_enableMPR, m_idTexture, m_rotationMatrix, m_stateMPRInput, and m_Threshold.
 {
     m_bInitialized = false;
     m_Threshold.push_back(0.0f);
     m_blender=0.5f;
     m_rotationMatrix.identity();
     m_idTexture.clear();
     m_enableMPR=false;
     m_stateMPRInput=false;
 }
Member Function Documentation
createBuffers()
void vmtkRender3D::createBuffers () private
creates vertex arrays and their buffer data.
Definition at line 235 of file vmtkRender3D.cpp.
References eboCube, eboRenderPlane, vaosCube, vaosRenderPlane, vboCube, and vboRenderPlane.
Referenced by initialize().
 {
     /*create buffers to Cube*/
     glGenVertexArrays(1, &vaosCube);
     glGenBuffers(1, &vboCube);
     glGenBuffers(1, &eboCube);
     /*create buffer to RenderPlane */
     glGenVertexArrays(1, &vaosRenderPlane);
     glGenBuffers(1, &vboRenderPlane);
     glGenBuffers(1, &eboRenderPlane);
 }
createVectorPlanes()
void vmtkRender3D::createVectorPlanes () private
defines the position and texture coordinates of the four vertices of a plane.
Definition at line 117 of file vmtkRender3D.cpp.
References v1, v2, v3, v4, vt1, vt2, vt3, and vt4.
Referenced by initialize().
 {
     v1=vmath::Vector2f(-1.0f,-1.0f);
     v2=vmath::Vector2f(1.0f,-1.0f);
     v3=vmath::Vector2f(1.0f,1.0f);
     v4=vmath::Vector2f(-1.0f,1.0f);
     vt1=vmath::Vector2f(0.0f,0.0f);
     vt2=vmath::Vector2f(1.0f,0.0f);
     vt3=vmath::Vector2f(1.0f,1.0f);
     vt4=vmath::Vector2f(0.0f,1.0f);
 }
currentActivateTexture()
int vmtkRender3D::currentActivateTexture ()
currentActivateTexture
Returns
number of the current texture activated.
Definition at line 39 of file vmtkRender3D.cpp.
Referenced by loadTransferFunctionsToTexture(), loadVolumesToTextures(), and raycastingMultiVolume().
{
     GLint nn;
     glGetIntegerv(GL_ACTIVE_TEXTURE, &nn);
     return nn-GL_TEXTURE0;
 }
drawCube()
void vmtkRender3D::drawCube () private
draws a cube.
Definition at line 590 of file vmtkRender3D.cpp.
References vaosCube.
Referenced by itlDrawColorCube().
 {
     glBindVertexArray(vaosCube);
     GLsizei count [] = {4, 4, 4, 4, 4, 4};
     const GLvoid *indices[] = {0,
                                (const GLvoid *)(sizeof(GLushort) * 4),
                                (const GLvoid *)(sizeof(GLushort) * 8),
                                (const GLvoid *)(sizeof(GLushort) * 12),
                                (const GLvoid *)(sizeof(GLushort) * 16),
                                (const GLvoid *)(sizeof(GLushort) * 20)};
     glMultiDrawElements(GL_TRIANGLE_FAN, count, GL_UNSIGNED_SHORT, indices, 6);
     glBindVertexArray(0);
 }
drawPlaneRayTraced()
void vmtkRender3D::drawPlaneRayTraced () private
draws the plane from pre-render shader.
Definition at line 382 of file vmtkRender3D.cpp.
References vaosRenderPlane.
Referenced by raycastingMultiVolume().
 {
     glBindVertexArray(vaosRenderPlane);
     glDrawElements(GL_TRIANGLE_FAN, 4, GL_UNSIGNED_SHORT, 0);
     glBindVertexArray(0);
 }
generateTransferFunction()
void vmtkRender3D::generateTransferFunction (Import::ImgFormat * data, int & dim, unsigned char *& tf)
generateTransferFunction
Parameters
[in] data volume information's.
[in] texbuffer buffer of the volume equalizer.
[out] tf buffer transfer function.
Definition at line 196 of file vmtkRender3D.cpp.
References TransferFunction::GetGrayScaleTF(), and Import::ImgFormat::nbitsalloc.
Referenced by loadTransferFunctionsToTexture().
{
     TransferFunction tfunc;
     tfunc.GetGrayScaleTF (4, 0, pow(2,data->nbitsalloc), &dim, &tf, data->nbitsalloc);
 }
getAcquisition()
Import::ImgFormat * vmtkRender3D::getAcquisition (int id)
get acquisition of the volumes.
Parameters
[in] id vector index of the volume.
Returns
volume informations for index selected.
Definition at line 62 of file vmtkRender3D.cpp.
References m_data.
Referenced by keyboard().
{
     if(id > (int) m_data.size()-1){
         std::cerr<<"Id out range."<<std::endl;
         return NULL;
     }
     return m_data[id];
 }
getMaxSliceLeft()
int vmtkRender3D::getMaxSliceLeft ()
gets the maximum number of the slices from the axis X.
Definition at line 605 of file vmtkRender3D.cpp.
References m_maxSliceLeft.
Referenced by keyboard().
 {
     return m_maxSliceLeft;
 }
initDrawCube()
void vmtkRender3D::initDrawCube ()
initializes the geometry of a cube to be rendered for getting back and front depth maps.
Definition at line 419 of file vmtkRender3D.cpp.
References eboCube, m_fClipXLeft, m_fClipXRight, m_fClipYBottom, m_fClipYTop, m_fClipZBack, m_fClipZFront, vaosCube, vboCube, vc1, vc10, vc11, vc12, vc13, vc14, vc15, vc16, vc17, vc18, vc19, vc2, vc20, vc21, vc22, vc23, vc24, vc3, vc4, vc5, vc6, vc7, vc8, and vc9.
Referenced by initialize(), and setClipLeftX().
{
     const float clip_x_left = m_fClipXLeft;
     const float clip_x_right = m_fClipXRight;
     const float clip_y_top = m_fClipYTop;
     const float clip_y_bottom = m_fClipYBottom;
     const float clip_z_front = m_fClipZBack;
     const float clip_z_back = m_fClipZFront;
     //left side
     vc1=vmath::Vector3f(clip_x_left, clip_y_bottom, clip_z_back);
     vc2=vmath::Vector3f(clip_x_left, clip_y_bottom, clip_z_front);
     vc3=vmath::Vector3f(clip_x_left, clip_y_top, clip_z_front);
     vc4=vmath::Vector3f(clip_x_left, clip_y_top, clip_z_back);
     //front side
     vc5=vmath::Vector3f(clip_x_left, clip_y_top, clip_z_front);
     vc6=vmath::Vector3f(clip_x_left, clip_y_bottom, clip_z_front);
     vc7=vmath::Vector3f(clip_x_right, clip_y_bottom, clip_z_front);
     vc8=vmath::Vector3f(clip_x_right, clip_y_top, clip_z_front);
     //right side
     vc9=vmath::Vector3f(clip_x_right, clip_y_top, clip_z_back);
     vc10=vmath::Vector3f(clip_x_right, clip_y_top, clip_z_front);
     vc11=vmath::Vector3f(clip_x_right, clip_y_bottom, clip_z_front);
     vc12=vmath::Vector3f(clip_x_right, clip_y_bottom, clip_z_back);
     //back side
     vc13=vmath::Vector3f(clip_x_right, clip_y_top, clip_z_back);
     vc14=vmath::Vector3f(clip_x_right, clip_y_bottom, clip_z_back);
     vc15=vmath::Vector3f(clip_x_left, clip_y_bottom, clip_z_back);
     vc16=vmath::Vector3f(clip_x_left, clip_y_top, clip_z_back);
     //bottom
     vc17=vmath::Vector3f(clip_x_left, clip_y_bottom, clip_z_back);
     vc18=vmath::Vector3f(clip_x_right, clip_y_bottom, clip_z_back);
     vc19=vmath::Vector3f(clip_x_right, clip_y_bottom, clip_z_front);
     vc20=vmath::Vector3f(clip_x_left, clip_y_bottom, clip_z_front);
     //top
     vc21=vmath::Vector3f(clip_x_left, clip_y_top, clip_z_back);
     vc22=vmath::Vector3f(clip_x_left, clip_y_top, clip_z_front);
     vc23=vmath::Vector3f(clip_x_right, clip_y_top, clip_z_front);
     vc24=vmath::Vector3f(clip_x_right, clip_y_top, clip_z_back);
     VertexDataCube vertices[] = {
         {vc1},  // 0
         {vc2},  // 1
         {vc3},  // 2
         {vc4},  // 3
         {vc5},  // 4
         {vc6},  // 5
         {vc7},  // 6
         {vc8},  // 7
         {vc9},  // 8
         {vc10}, // 9
         {vc11}, // 10
         {vc12}, // 11
         {vc13}, // 12
         {vc14}, // 13
         {vc15}, // 14
         {vc16}, // 15
         {vc17}, // 16
         {vc18}, // 17
         {vc19}, // 18
         {vc20}, // 19
         {vc21}, // 20
         {vc22}, // 21
         {vc23}, // 22
         {vc24} // 23
     };
     GLushort indices[] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23};
     glBindVertexArray(vaosCube);
     glBindBuffer(GL_ARRAY_BUFFER, vboCube);
     glBufferData(GL_ARRAY_BUFFER, 24 * sizeof(VertexDataCube), vertices, GL_DYNAMIC_DRAW);
     glEnableVertexAttribArray(0);
     glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, (const void *) 0);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, eboCube);
     glBufferData(GL_ELEMENT_ARRAY_BUFFER, 24 * sizeof(GLushort), indices, GL_DYNAMIC_DRAW);
 }
initialize()
void vmtkRender3D::initialize (int width, int height)
initializes 3D volume rendering.
Definition at line 87 of file vmtkRender3D.cpp.
References Shaders::carregueShaders(), createBuffers(), createVectorPlanes(), height, initDrawCube(), initRenderPlane(), loadTransferFunctionsToTexture(), loadVolumesToTextures(), m_BackFBO, m_bInitialized, m_ColorShader, m_fClipXLeft, m_fClipXRight, m_fClipYBottom, m_fClipYTop, m_fClipZBack, m_fClipZFront, m_FrontFBO, m_iHeight, m_iWidth, m_RaytraceShader, and width.
Referenced by init().
 {
     Shaders sh;
     this->m_iHeight = width;
     this->m_iWidth = height;
     this->m_BackFBO = new vmtkFrameBufferObject(width, height);
     this->m_FrontFBO = new vmtkFrameBufferObject(width, height);
     m_fClipXLeft = -1.0f;
     m_fClipXRight = 1.0f;
     m_fClipYTop = 1.0f;
     m_fClipYBottom = -1.0f;
     m_fClipZBack = 1.0f;
     m_fClipZFront = -1.0f;
     m_ColorShader = sh.carregueShaders("../../shaders/position_is_color.vert", "../../shaders/position_is_color.frag");
     m_RaytraceShader = sh.carregueShaders("../../shaders/raytrace.vert", "../../shaders/castregister_with_planar_clipping.frag");
     loadVolumesToTextures();
     loadTransferFunctionsToTexture();
     createVectorPlanes();
     createBuffers();
     initDrawCube();
     initRenderPlane();
     m_bInitialized = true;
 }
initRenderPlane()
void vmtkRender3D::initRenderPlane () private
initializes the plane to be input into the graphics pipeline
Definition at line 248 of file vmtkRender3D.cpp.
References eboRenderPlane, v1, v2, v3, v4, vaosRenderPlane, vboRenderPlane, vt1, vt2, vt3, and vt4.
Referenced by initialize().
 {
      VertexData vertices[] = {
         {v1, vt1},  // v0
         {v2, vt2}, // v1
         {v3, vt3}, // v2
         {v4, vt4},  // v3
     };
     GLushort indices[] = { 0,  1,  2,  3};
     glBindVertexArray(vaosRenderPlane);
     glBindBuffer(GL_ARRAY_BUFFER, vboRenderPlane);
     glBufferData(GL_ARRAY_BUFFER, 4 * sizeof(VertexData), vertices, GL_STATIC_DRAW);
     int offset = 0;
     glEnableVertexAttribArray(0);
     glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, sizeof(VertexData), (const void *)(intptr_t)offset);
     offset += sizeof(vmath::Vector2f);
     glEnableVertexAttribArray(1);
     glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, sizeof(VertexData), (const void *)(intptr_t)offset);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, eboRenderPlane);
     glBufferData(GL_ELEMENT_ARRAY_BUFFER, 4 * sizeof(GLushort), indices, GL_STATIC_DRAW);
     glBindVertexArray(0);
 }
itlDrawColorCube()
void vmtkRender3D::itlDrawColorCube (vmath::Matrix4f mvp)
draws a unit cube to get the front and the back depth maps of the volume cube, after updating the clipping plane values.
Parameters
[in] mvp projection*modelview matrix.
Definition at line 405 of file vmtkRender3D.cpp.
References drawCube(), m_ColorShader, and m_scaleFactors.
Referenced by preRender().
 {
 //  initDrawCube();
     glUseProgram(m_ColorShader);
     GLuint id = glGetUniformLocation(m_ColorShader,"mvp_matrix");
     glUniformMatrix4fv(id, 1, GL_FALSE, mvp);
     glUniform4fv(glGetUniformLocation(m_ColorShader,"scaleFactors"), 1, m_scaleFactors[0]);
     drawCube();
     glUseProgram(0);
 }
loadTransferFunctionsToTexture()
void vmtkRender3D::loadTransferFunctionsToTexture () private
Loads transfer Functions to textures 1D.
Definition at line 219 of file vmtkRender3D.cpp.
References currentActivateTexture(), generateTransferFunction(), m_data, m_idTF, m_pos_activate, and texture1DFromTransferFunction().
Referenced by initialize().
 {
     for(int i = 0; i < (int) m_data.size(); i++){
         int dim;
         unsigned char *tf;
         generateTransferFunction(m_data[i],dim,tf);
         GLuint idTransferFunction;
         glActiveTexture(GL_TEXTURE0+m_pos_activate);
         m_pos_activate = currentActivateTexture()+1;
         texture1DFromTransferFunction(dim,tf,idTransferFunction);
         m_idTF.push_back(idTransferFunction);
         delete [] tf;
     }
 }
loadVolumesToTextures()
void vmtkRender3D::loadVolumesToTextures () private
loads volumes to textures 3D.
Definition at line 175 of file vmtkRender3D.cpp.
References currentActivateTexture(), m_data, m_idTexture, m_map, m_pos_activate, m_Threshold, mapEqualizeHistogramVolume(), texture3DFromVolume(), threshold, and volumeEqualizer().
Referenced by initialize().
 {
     int threshold = 23;
     m_pos_activate = 0;
     for (int i = 0; i< (int) m_data.size(); i++){
         unsigned short *texbuffer;
         unsigned short *map;
         mapEqualizeHistogramVolume(m_data[i],map);
         m_map.push_back(map);
         volumeEqualizer(m_data[i],m_map[i],texbuffer);
         GLuint idTexture;
         glActiveTexture(GL_TEXTURE0+m_pos_activate);
         m_pos_activate = currentActivateTexture()+1;
         texture3DFromVolume(m_data[i],texbuffer,idTexture);
         m_idTexture.push_back(idTexture);
 //        delete [] texbuffer;
 //        delete [] map;
     }
     m_Threshold[0] = m_map[0][(unsigned short)(threshold)] / (pow(2, m_data[0]->nbitsalloc) - 1);
 }
mapEqualizeHistogramVolume()
void vmtkRender3D::mapEqualizeHistogramVolume (Import::ImgFormat * data, unsigned short *& map)
mapEqualizeHistogramVolume
Parameters
[in] data volume information's.
[out] map histogram equalization mapping of the volume.
Definition at line 130 of file vmtkRender3D.cpp.
References Import::ImgFormat::buffer, Import::ImgFormat::dims, Equalize::EqualizeHistogram(), Import::ImgFormat::nbitsalloc, and Import::ImgFormat::umax.
Referenced by loadVolumesToTextures().
{
     Equalize eq;
     // Equaliza o histograma para aumentar a escala dinamica das intensidades
     // como uma forma de contornar a perda de resolucao durante normalizacao
     // feita pelas unidades de textura
     eq.EqualizeHistogram (data->dims[0], data->dims[1], data->dims[2],
             (reinterpret_cast<unsigned short*>(data->buffer)),
                         data->nbitsalloc, data->umax, &map);
 }
maximumDimension()
float vmtkRender3D::maximumDimension (float vrd[])
maximumDimension
Parameters
vrd (real Dimension of the volume).
Returns
Maximum dimension of the volume.
Definition at line 20 of file vmtkRender3D.cpp.
References std::max().
Referenced by setAcquisition().
{
     return std::max(std::max(vrd[0], vrd[1]), vrd[2]);
 }
phyDimension()
vmath::Vector4f vmtkRender3D::phyDimension (Import::ImgFormat * data)
phyDimension
Parameters
[in] data volume information's.
Returns
Physical dimension.
Definition at line 32 of file vmtkRender3D.cpp.
References Import::ImgFormat::dims, and phyDimensions.
Referenced by setAcquisition().
{
     float phyDimensions[4];
     for (int i = 0; i < 3; i++){ phyDimensions[i] = data->dims[i]; }
     phyDimensions[3]=1.0;
     return vmath::Vector4<float>(phyDimensions);
 }
preRender()
void vmtkRender3D::preRender (vmath::Matrix4f mvp)
renders the color cube in the fbos.
Parameters
[in] mvp modelview matrix.
Definition at line 289 of file vmtkRender3D.cpp.
References vmtkFrameBufferObject::binding(), itlDrawColorCube(), m_BackFBO, m_FrontFBO, m_iHeight, m_iWidth, and vmtkFrameBufferObject::releasing().
Referenced by render().
 {
     glEnable(GL_CULL_FACE);
     glCullFace(GL_FRONT);
     this->m_BackFBO->binding();
     glClearColor(0.,0.,0.,1.);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);     //clear buffers
     glViewport(0,0,m_iWidth, m_iHeight);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     this->itlDrawColorCube(mvp);
     this->m_BackFBO->releasing();
     glCullFace(GL_BACK);
     this->m_FrontFBO->binding();
     glClearColor(0.,0.,0.,1.);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);     //clear buffers
     glViewport(0,0,m_iWidth,m_iHeight);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     this->itlDrawColorCube(mvp);
     this->m_FrontFBO->releasing();
 }
raycastingMultiVolume()
void vmtkRender3D::raycastingMultiVolume () private
raycasts through the color cube.
Definition at line 313 of file vmtkRender3D.cpp.
References currentActivateTexture(), drawPlaneRayTraced(), vmtkFrameBufferObject::getTexture(), m_BackFBO, m_blender, m_data, m_enableMPR, m_equationPlaneForMPR, m_FrontFBO, m_idTexture, m_idTF, m_iHeight, m_invRegMatrix, m_iWidth, m_phyDimensions, m_pos_activate, m_RaytraceShader, m_stateMPRInput, m_Threshold, and NumberToString().
Referenced by render().
 {
     glClearColor(0.,0.,0.,1.);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);      //clear buffers
     glViewport(0,0,m_iWidth,m_iHeight);
     glUseProgram(m_RaytraceShader);
     glUniform1i(glGetUniformLocation(m_RaytraceShader,"width"),  m_data[0]->dims[0]);
     glUniform1i(glGetUniformLocation(m_RaytraceShader,"height"), m_data[0]->dims[1]);
     glUniform1i(glGetUniformLocation(m_RaytraceShader,"depth"),  m_data[0]->dims[2]);
     glUniform1i(glGetUniformLocation(m_RaytraceShader,"steps_mode"), 300);
     /*Volumes*/
     m_pos_activate = 0;
     glUniform1i(glGetUniformLocation(m_RaytraceShader,"nVolumes"), m_data.size());
     /*volumes 3D */
     for(int i = 0; i < (int) m_data.size(); i++){
         glActiveTexture(GL_TEXTURE0+m_pos_activate);
         glBindTexture(GL_TEXTURE_3D, m_idTexture[i]);
         glTexParameteri(GL_TEXTURE_3D,GL_TEXTURE_MIN_FILTER, GL_LINEAR);
         glTexParameteri(GL_TEXTURE_3D,GL_TEXTURE_MAG_FILTER, GL_LINEAR);
         std::string nameVolume = "vTexture"+NumberToString(i);
         glUniform1i(glGetUniformLocation(m_RaytraceShader, nameVolume.c_str() ), m_pos_activate );
         m_pos_activate = currentActivateTexture()+1;
     }
     /*Transfer Function*/
     for(int i = 0; i < (int) m_data.size(); i++){
         glActiveTexture(GL_TEXTURE0+m_pos_activate);
         glBindTexture(GL_TEXTURE_1D, m_idTF[i]);
         std::string nameTF = "vTF"+NumberToString(i);
         glUniform1i(glGetUniformLocation(m_RaytraceShader, nameTF.c_str()),m_pos_activate);
         m_pos_activate = currentActivateTexture()+1;
     }
     glUniform4fv(glGetUniformLocation(m_RaytraceShader,"phyDimensions"), m_data.size(), (const GLfloat*)m_phyDimensions);
     //register matrix
     glUniformMatrix4fv(glGetUniformLocation(m_RaytraceShader,"inv_registration_matrix"), m_data.size()-1, GL_TRUE , (const GLfloat*) m_invRegMatrix);
     if(m_stateMPRInput){
         glUniform1i(glGetUniformLocation(m_RaytraceShader,"enableMPR"), m_enableMPR);
         if(m_enableMPR){
             glUniform4fv(glGetUniformLocation(m_RaytraceShader,"clipping_plane"), 1, m_equationPlaneForMPR);
         }
     }
     else{
         glUniform1i(glGetUniformLocation(m_RaytraceShader,"enableMPR"), false);
     }
     glUniform1f(glGetUniformLocation(m_RaytraceShader,"noise_threshold"), m_Threshold[0]);
     glUniform1f(glGetUniformLocation(m_RaytraceShader,"blending_factor"), m_blender);
     /*Front-Back face*/
     glActiveTexture(GL_TEXTURE0+m_pos_activate);
     glBindTexture(GL_TEXTURE_2D, this->m_BackFBO->getTexture());
     glUniform1i(glGetUniformLocation(m_RaytraceShader,"backface_fbo"), m_pos_activate);
     m_pos_activate = currentActivateTexture()+1;
     glActiveTexture(GL_TEXTURE0+m_pos_activate);
     glBindTexture(GL_TEXTURE_2D, this->m_FrontFBO->getTexture());
     glUniform1i(glGetUniformLocation(m_RaytraceShader,"frontface_fbo"), m_pos_activate);
     drawPlaneRayTraced();
     glUseProgram(0);
 }
readMatrix()
bool vmtkRender3D::readMatrix (const char * s, vmath::Matrix4f & invRM)
reads the co-register matrix.
Parameters
[in] s co-register matrix file name.
[out] invRM inverse matrix.
Returns
Definition at line 502 of file vmtkRender3D.cpp.
Referenced by main().
 {
     int k = 0;
     float x;
     vmath::Matrix4f registrationMatrix;
     std::ifstream file(s);
     if(file.is_open())
     {
         while(file)
         {
             file >> x;
             registrationMatrix.data[k] = x;
             k++;
         }
         std::cout << "Co-register matrix" << std::endl;
         for (int i = 0; i < 4; i++)
         {
             for (int j = 0; j < 4; j++)
                 std::cout << registrationMatrix.at(i,j) << " ";
             std::cout << std::endl;
         }
         file.close();
         invRM = registrationMatrix.inverse();
         return true;
     }
     else
         std::cerr << "Matrix not found!" << std::endl;
     return false;
 }
readPlane()
bool vmtkRender3D::readPlane (const char * s, vmath::Vector4f & eqp)
readPlane
Parameters
[in] s string file name.
[out] eqp Equation of the plane for multiplanar reformation.
Returns
Definition at line 534 of file vmtkRender3D.cpp.
Referenced by main().
 {
     int k = 0;
     float x;
     std::ifstream file(s);
     float t[4];
     if(file.is_open())
     {
         while(file)
         {
             file >> x;
             t[k] = x;
             k++;
         }
         vmath::Vector4f eqPlane(t);
         std::cout << "Equation Plane" << std::endl;
         for (int i = 0; i < 4; i++)
         {
             std::cout << eqPlane[i] << std::endl;
         }
         file.close();
         eqp = eqPlane;
         return true;
     }
     else
         std::cerr << "Equation plane not found!" << std::endl;
     return false;
 }
render()
void vmtkRender3D::render ()
renders the data with the specified redering mode.
Definition at line 278 of file vmtkRender3D.cpp.
References m_modelViewMatrix, m_projectionMatrix, m_rotationMatrix, m_scalationMatrix, m_translationMatrix, preRender(), and raycastingMultiVolume().
Referenced by drawProxyGeometry().
 {
     vmath::Matrix4f mvp;
     m_modelViewMatrix=m_translationMatrix*m_rotationMatrix*m_scalationMatrix;
     mvp = m_projectionMatrix * m_modelViewMatrix;
     preRender(mvp);
     raycastingMultiVolume();
 }
resize()
void vmtkRender3D::resize (int width, int height)
resizes the dimensions of the display.
Parameters
[in] w width of image.
[in] h height of image.
Definition at line 389 of file vmtkRender3D.cpp.
References height, m_BackFBO, m_FrontFBO, m_iHeight, m_iWidth, m_projectionMatrix, and width.
Referenced by reshape().
 {
     const float zNear = -100.0f, zFar =100.0f; //, fov = 45.0f;
     m_projectionMatrix = m_projectionMatrix.createOrtho(-1.0f,1.0f,-1.0f,1.0f,zNear,zFar);
     delete this->m_BackFBO;
     delete this->m_FrontFBO;
     this->m_BackFBO = new vmtkFrameBufferObject(width, height);
     this->m_FrontFBO = new vmtkFrameBufferObject(width, height);
     this->m_iHeight = height;
     this->m_iWidth = width;
 }
scaleFactors()
vmath::Vector4f vmtkRender3D::scaleFactors (float vrd[], float maxDim)
scaleFactors
Parameters
[in] vrd eal Dimension of the volume.
[in] maxDim Maximum dimension of the volume.
Returns
scale factor of the volume.
Definition at line 24 of file vmtkRender3D.cpp.
Referenced by setAcquisition().
 {
     float scaleFactor[4];
     for (int i = 0; i < 3; i++){ scaleFactor[i] = vrd[i] / maxDim; }
     scaleFactor[3]=1.0;
     return vmath::Vector4<float>(scaleFactor);
 }
setAcquisition()
void vmtkRender3D::setAcquisition (std::vector< Import::ImgFormat *> acqVector)
sets the volumes to be registered.
Parameters
[in] acqVector vector of the volumes.
Definition at line 45 of file vmtkRender3D.cpp.
References m_data, m_maxSliceLeft, m_phyDimensions, m_scaleFactors, maximumDimension(), phyDimension(), scaleFactors(), and volumeRealDimension().
Referenced by main().
 {
     float vrd[3];
     float maxDim;
     m_scaleFactors = new vmath::Vector4f[acqVector.size()];
     m_phyDimensions = new vmath::Vector4f[acqVector.size()];
     for (int i = 0; i < (int) acqVector.size(); i++) {
         m_data.push_back(acqVector[i]);
         volumeRealDimension( m_data[i], vrd );
         maxDim = maximumDimension(vrd);
         m_scaleFactors[i] = scaleFactors(vrd, maxDim);
         m_phyDimensions[i] = phyDimension(m_data[i]);
     }
     m_maxSliceLeft =  m_data[0]->dims[0];
 }
setBlender()
void vmtkRender3D::setBlender (float blender)
sets the blender factor.
Parameters
[in] blender factor.
Definition at line 81 of file vmtkRender3D.cpp.
References blender, and m_blender.
Referenced by keyboard().
 {
     m_blender = blender;
     std::cout<<"blender: "<< blender <<std::endl;
 }
setClipLeftX()
void vmtkRender3D::setClipLeftX (float left_x)
sets the clipping plane.
Parameters
[in] slice
Definition at line 584 of file vmtkRender3D.cpp.
References initDrawCube(), m_data, and m_fClipXLeft.
Referenced by keyboard().
 {
     m_fClipXLeft = (left_x/m_data[0]->dims[0])*2-1;
     initDrawCube();
 }
setEnableMPR()
void vmtkRender3D::setEnableMPR (bool enableMPR)
setEnableMPR
Parameters
[in] enableMPR enable MPR from keys interaction's, if equation file exist.
Definition at line 564 of file vmtkRender3D.cpp.
References enableMPR, and m_enableMPR.
Referenced by keyboard(), and main().
{
     m_enableMPR = enableMPR;
 }
setMPR()
void vmtkRender3D::setMPR (vmath::Vector4f eqp)
setMPR
Parameters
[in] eqp equation plane for multiplanar reformatting.
Definition at line 580 of file vmtkRender3D.cpp.
References m_equationPlaneForMPR.
Referenced by main().
{
     m_equationPlaneForMPR = eqp;
 }
setRotation()
void vmtkRender3D::setRotation (float ax, float ay, float az)
sets the rotation matrix.
Parameters
[in] rotation matrix.
Definition at line 70 of file vmtkRender3D.cpp.
References m_rotationMatrix.
Referenced by keyboard().
 {
     m_rotationMatrix = m_rotationMatrix.createRotationAroundAxis(ax,ay,az);
 }
setStateMPRInput()
void vmtkRender3D::setStateMPRInput (bool stateMPRInput)
setStateMPRInput
Parameters
[in] stateMPRInput file input status for MPR.
Definition at line 568 of file vmtkRender3D.cpp.
References m_stateMPRInput.
Referenced by main().
 {
     m_stateMPRInput=stateMPRInput;
 }
setThreshold()
void vmtkRender3D::setThreshold (int threshold)
sets the threshold.
Parameters
[in] threshold.
Definition at line 75 of file vmtkRender3D.cpp.
References m_data, m_map, and m_Threshold.
Referenced by keyboard().
 {
     m_Threshold[0] = m_map[0][(unsigned short)(threshold)] / (pow(2, m_data[0]->nbitsalloc) - 1);
     std::cout<<"Threshold: "<< m_Threshold[0] <<std::endl;
 }
setVectorInvMatrixReg()
void vmtkRender3D::setVectorInvMatrixReg (std::vector< vmath::Matrix4f > imr)
setVectorInvMatrixReg
Parameters
[in] imr vector of the inverse matrix register.
Definition at line 573 of file vmtkRender3D.cpp.
References m_invRegMatrix.
Referenced by main().
{
     m_invRegMatrix = new vmath::Matrix4f[ (int) imr.size() ];
     for(int i = 0; i < (int) imr.size(); i++){
         m_invRegMatrix[i] = imr[i];
     }
 }
texture1DFromTransferFunction()
void vmtkRender3D::texture1DFromTransferFunction (int dim, unsigned char * tf, GLuint & idTF)
texture1DFromTransferFunction
Parameters
[in] dim dimension transfer fucntion mapping.
[in] tf buffer transfer function.
[out] idTF id transfer function texture (texture name).
Definition at line 201 of file vmtkRender3D.cpp.
Referenced by loadTransferFunctionsToTexture().
{
     GLuint idTransferFunction;
     glGenTextures(1, &idTransferFunction);
     glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
     // Carrega a funcao de transferencia como textura 1D
     glBindTexture(GL_TEXTURE_1D, idTransferFunction);
     glTexImage1D(GL_TEXTURE_1D, 0, GL_RGBA, dim, 0, GL_RED,
            GL_UNSIGNED_BYTE, tf);
     glTexParameteri(GL_TEXTURE_1D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
     glTexParameteri(GL_TEXTURE_1D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     glTexParameteri(GL_TEXTURE_1D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_1D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_1D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
     idTF = idTransferFunction;
 }
texture3DFromVolume()
void vmtkRender3D::texture3DFromVolume (Import::ImgFormat * data, unsigned short * texbuffer, GLuint & idTexture)
texture3DFromVolume
Parameters
[in] data volume information's.
[in] texbuffer buffer of the volume equalizer.
[out] idTexture id volume texture (texture name).
Definition at line 156 of file vmtkRender3D.cpp.
References Import::ImgFormat::dims.
Referenced by loadVolumesToTextures().
{
     GLuint idTexture;
     glGenTextures(1, &idTexture);
     // Define a unidade de alinhamento nos acessos
     glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
     glBindTexture(GL_TEXTURE_3D, idTexture);
     glTexImage3D(GL_TEXTURE_3D, 0, GL_RGBA, data->dims[0],
            data->dims[1], data->dims[2], 0, GL_RED,
            GL_UNSIGNED_SHORT, texbuffer);
     glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
     glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
     idTex = idTexture;
 }
volumeEqualizer()
void vmtkRender3D::volumeEqualizer (Import::ImgFormat * data, unsigned short * map, unsigned short *& texbuffer)
volumeEqualizer
Parameters
[in] data volume information's.
[in] map histogram equalization mapping of the volume.
[out] texbuffer buffer of the volume equalizer.
Definition at line 140 of file vmtkRender3D.cpp.
References Import::ImgFormat::buffer, and Import::ImgFormat::dims.
Referenced by loadVolumesToTextures().
{
     int intensidade, di, iz, iy, ix, volSize;
     volSize = data->dims[0]*data->dims[1]*data->dims[2];
     texbuffer = new unsigned short[volSize];
     memset(texbuffer, 0x00, volSize*sizeof(unsigned short));
     for (di=0, iz = 0; iz < data->dims[2]; iz++) {
         for (iy =0; iy < data->dims[1]; iy++) {
           for (ix =0; ix < data->dims[0]; ix++) {
             intensidade = (int) ((reinterpret_cast<unsigned short*>(data->buffer))[iz*data->dims[0]*data->dims[1]+iy*data->dims[0]+ix]);
             texbuffer[di++] = (unsigned short)(map[intensidade]);
           }
         }
     }
 }
volumeRealDimension()
void vmtkRender3D::volumeRealDimension (Import::ImgFormat * data, float vrd[])
volumeRealDimension
Parameters
[in] data volume information's.
[out] vrd real Dimension of the volume.
Definition at line 16 of file vmtkRender3D.cpp.
References Import::ImgFormat::dims, and Import::ImgFormat::space.
Referenced by setAcquisition().
{
     for(int i = 0; i < 3; i++) { vrd[i] = data->dims[i] * data->space[i]; }
 }
Member Data Documentation
eboCube
GLuint vmtkRender3D::eboCube private
drawCube: element array buffer
Definition at line 233 of file vmtkRender3D.h.
Referenced by createBuffers(), and initDrawCube().
eboRenderPlane
GLuint vmtkRender3D::eboRenderPlane private
RenderPlane: element array buffer
Definition at line 233 of file vmtkRender3D.h.
Referenced by createBuffers(), and initRenderPlane().
eboResultPlane
GLuint vmtkRender3D::eboResultPlane private
renderResult: element array buffer
Definition at line 233 of file vmtkRender3D.h.
m_BackFBO
vmtkFrameBufferObject* vmtkRender3D::m_BackFBO private
framebuffer object for back side
Definition at line 293 of file vmtkRender3D.h.
Referenced by initialize(), preRender(), raycastingMultiVolume(), and resize().
m_bInitialized
bool vmtkRender3D::m_bInitialized private
whether the volume renderer is initialized ?
Definition at line 296 of file vmtkRender3D.h.
Referenced by initialize(), and vmtkRender3D().
m_blender
float vmtkRender3D::m_blender private
blender for the reference and float volumes.
Definition at line 220 of file vmtkRender3D.h.
Referenced by raycastingMultiVolume(), setBlender(), and vmtkRender3D().
m_ColorShader
GLuint vmtkRender3D::m_ColorShader private
pre-processing shader to get front and back planes
Definition at line 230 of file vmtkRender3D.h.
Referenced by initialize(), and itlDrawColorCube().
m_data
std::vector<Import::ImgFormat*> vmtkRender3D::m_data private
data vector of the volumes.
Definition at line 224 of file vmtkRender3D.h.
Referenced by getAcquisition(), loadTransferFunctionsToTexture(), loadVolumesToTextures(), raycastingMultiVolume(), setAcquisition(), setClipLeftX(), and setThreshold().
m_enableMPR
bool vmtkRender3D::m_enableMPR private
enable multiplanar reformatting
Definition at line 227 of file vmtkRender3D.h.
Referenced by raycastingMultiVolume(), setEnableMPR(), and vmtkRender3D().
m_equationPlaneForMPR
vmath::Vector4f vmtkRender3D::m_equationPlaneForMPR private
equation plane for multiplanar reformatting
Definition at line 226 of file vmtkRender3D.h.
Referenced by raycastingMultiVolume(), and setMPR().
m_fClipXLeft
float vmtkRender3D::m_fClipXLeft private
x left clip plane
Definition at line 273 of file vmtkRender3D.h.
Referenced by initDrawCube(), initialize(), and setClipLeftX().
m_fClipXRight
float vmtkRender3D::m_fClipXRight private
x right clip plane
Definition at line 274 of file vmtkRender3D.h.
Referenced by initDrawCube(), and initialize().
m_fClipYBottom
float vmtkRender3D::m_fClipYBottom private
y bottom clip plane
Definition at line 276 of file vmtkRender3D.h.
Referenced by initDrawCube(), and initialize().
m_fClipYTop
float vmtkRender3D::m_fClipYTop private
y top clip plane
Definition at line 275 of file vmtkRender3D.h.
Referenced by initDrawCube(), and initialize().
m_fClipZBack
float vmtkRender3D::m_fClipZBack private
z back clip plane
Definition at line 277 of file vmtkRender3D.h.
Referenced by initDrawCube(), and initialize().
m_fClipZFront
float vmtkRender3D::m_fClipZFront private
z front clip plane
Definition at line 278 of file vmtkRender3D.h.
Referenced by initDrawCube(), and initialize().
m_FrontFBO
vmtkFrameBufferObject* vmtkRender3D::m_FrontFBO private
framebuffer object for front side
Definition at line 292 of file vmtkRender3D.h.
Referenced by initialize(), preRender(), raycastingMultiVolume(), and resize().
m_idTexture
std::vector<GLuint> vmtkRender3D::m_idTexture private
Definition at line 225 of file vmtkRender3D.h.
Referenced by loadVolumesToTextures(), raycastingMultiVolume(), and vmtkRender3D().
m_idTF
std::vector<GLuint> vmtkRender3D::m_idTF private
id textures
Definition at line 225 of file vmtkRender3D.h.
Referenced by loadTransferFunctionsToTexture(), and raycastingMultiVolume().
m_iHeight
int vmtkRender3D::m_iHeight private
offscreen image height
Definition at line 280 of file vmtkRender3D.h.
Referenced by initialize(), preRender(), raycastingMultiVolume(), and resize().
m_invRegMatrix
vmath::Matrix4f* vmtkRender3D::m_invRegMatrix private
inverse matrix array for register
Definition at line 221 of file vmtkRender3D.h.
Referenced by raycastingMultiVolume(), and setVectorInvMatrixReg().
m_iWidth
int vmtkRender3D::m_iWidth private
offscreen image width
Definition at line 281 of file vmtkRender3D.h.
Referenced by initialize(), preRender(), raycastingMultiVolume(), and resize().
m_map
std::vector<unsigned short *> vmtkRender3D::m_map private
map vector of the volumes
Definition at line 222 of file vmtkRender3D.h.
Referenced by loadVolumesToTextures(), and setThreshold().
m_maxSliceLeft
int vmtkRender3D::m_maxSliceLeft private
dimension volume for X-axis
Definition at line 219 of file vmtkRender3D.h.
Referenced by getMaxSliceLeft(), and setAcquisition().
m_modelViewMatrix
vmath::Matrix4f vmtkRender3D::m_modelViewMatrix private
modelview transformation matrix
Definition at line 284 of file vmtkRender3D.h.
Referenced by render().
m_phyDimensions
vmath::Vector4f* vmtkRender3D::m_phyDimensions private
physical dimensions of volumes
Definition at line 289 of file vmtkRender3D.h.
Referenced by raycastingMultiVolume(), and setAcquisition().
m_projectionMatrix
vmath::Matrix4f vmtkRender3D::m_projectionMatrix private
projection transformation matrix
Definition at line 283 of file vmtkRender3D.h.
Referenced by render(), and resize().
m_RayTracedFBO
vmtkFrameBufferObject* vmtkRender3D::m_RayTracedFBO private
framebuffer object for raycasted image
Definition at line 294 of file vmtkRender3D.h.
m_RaytraceShader
GLuint vmtkRender3D::m_RaytraceShader private
raycast shader
Definition at line 231 of file vmtkRender3D.h.
Referenced by initialize(), and raycastingMultiVolume().
m_rotationMatrix
vmath::Matrix4f vmtkRender3D::m_rotationMatrix private
rotationMatrix transformation matrix
Definition at line 285 of file vmtkRender3D.h.
Referenced by render(), setRotation(), and vmtkRender3D().
m_scalationMatrix
vmath::Matrix4f vmtkRender3D::m_scalationMatrix private
scalationMatrix transformation matrix
Definition at line 286 of file vmtkRender3D.h.
Referenced by render().
m_scaleFactors
vmath::Vector4f* vmtkRender3D::m_scaleFactors private
scale factor for compensating distortions on the textures volumes
Definition at line 290 of file vmtkRender3D.h.
Referenced by itlDrawColorCube(), and setAcquisition().
m_stateMPRInput
bool vmtkRender3D::m_stateMPRInput private
state load equation for multiplanar reformatting
Definition at line 228 of file vmtkRender3D.h.
Referenced by raycastingMultiVolume(), setStateMPRInput(), and vmtkRender3D().
m_Threshold
std::vector<float> vmtkRender3D::m_Threshold private
threshold vector for volumes
Definition at line 223 of file vmtkRender3D.h.
Referenced by loadVolumesToTextures(), raycastingMultiVolume(), setThreshold(), and vmtkRender3D().
m_translationMatrix
vmath::Matrix4f vmtkRender3D::m_translationMatrix private
traslationMatrix transformation matrix
Definition at line 287 of file vmtkRender3D.h.
Referenced by render().
v1
vmath::Vector2f vmtkRender3D::v1 private
Position vectors of VertexData.
Definition at line 262 of file vmtkRender3D.h.
Referenced by createVectorPlanes(), and initRenderPlane().
v2
vmath::Vector2f vmtkRender3D::v2 private
Definition at line 262 of file vmtkRender3D.h.
Referenced by createVectorPlanes(), and initRenderPlane().
v3
vmath::Vector2f vmtkRender3D::v3 private
Definition at line 262 of file vmtkRender3D.h.
Referenced by createVectorPlanes(), and initRenderPlane().
v4
vmath::Vector2f vmtkRender3D::v4 private
Definition at line 262 of file vmtkRender3D.h.
Referenced by createVectorPlanes(), and initRenderPlane().
vaosCube
GLuint vmtkRender3D::vaosCube private
drawCube: vertex array object
Definition at line 233 of file vmtkRender3D.h.
Referenced by createBuffers(), drawCube(), and initDrawCube().
vaosRenderPlane
GLuint vmtkRender3D::vaosRenderPlane private
RenderPlane: vertex array object
Definition at line 233 of file vmtkRender3D.h.
Referenced by createBuffers(), drawPlaneRayTraced(), and initRenderPlane().
vaosResultPlane
GLuint vmtkRender3D::vaosResultPlane private
renderResult: vertex array object
Definition at line 233 of file vmtkRender3D.h.
vboCube
GLuint vmtkRender3D::vboCube private
drawCube: data buffer
Definition at line 233 of file vmtkRender3D.h.
Referenced by createBuffers(), and initDrawCube().
vboRenderPlane
GLuint vmtkRender3D::vboRenderPlane private
RenderPlane: data buffer
Definition at line 233 of file vmtkRender3D.h.
Referenced by createBuffers(), and initRenderPlane().
vboResultPlane
GLuint vmtkRender3D::vboResultPlane private
renderResult: data buffer
Definition at line 233 of file vmtkRender3D.h.
vc1
vmath::Vector3f vmtkRender3D::vc1 private
Position vectors of VertexDataCube.
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc10
vmath::Vector3f vmtkRender3D::vc10 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc11
vmath::Vector3f vmtkRender3D::vc11 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc12
vmath::Vector3f vmtkRender3D::vc12 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc13
vmath::Vector3f vmtkRender3D::vc13 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc14
vmath::Vector3f vmtkRender3D::vc14 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc15
vmath::Vector3f vmtkRender3D::vc15 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc16
vmath::Vector3f vmtkRender3D::vc16 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc17
vmath::Vector3f vmtkRender3D::vc17 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc18
vmath::Vector3f vmtkRender3D::vc18 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc19
vmath::Vector3f vmtkRender3D::vc19 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc2
vmath::Vector3f vmtkRender3D::vc2 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc20
vmath::Vector3f vmtkRender3D::vc20 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc21
vmath::Vector3f vmtkRender3D::vc21 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc22
vmath::Vector3f vmtkRender3D::vc22 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc23
vmath::Vector3f vmtkRender3D::vc23 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc24
vmath::Vector3f vmtkRender3D::vc24 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc3
vmath::Vector3f vmtkRender3D::vc3 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc4
vmath::Vector3f vmtkRender3D::vc4 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc5
vmath::Vector3f vmtkRender3D::vc5 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc6
vmath::Vector3f vmtkRender3D::vc6 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc7
vmath::Vector3f vmtkRender3D::vc7 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc8
vmath::Vector3f vmtkRender3D::vc8 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vc9
vmath::Vector3f vmtkRender3D::vc9 private
Definition at line 270 of file vmtkRender3D.h.
Referenced by initDrawCube().
vt1
vmath::Vector2f vmtkRender3D::vt1 private
Texture vectors of VertexData.
Definition at line 266 of file vmtkRender3D.h.
Referenced by createVectorPlanes(), and initRenderPlane().
vt2
vmath::Vector2f vmtkRender3D::vt2 private
Definition at line 266 of file vmtkRender3D.h.
Referenced by createVectorPlanes(), and initRenderPlane().
vt3
vmath::Vector2f vmtkRender3D::vt3 private
Definition at line 266 of file vmtkRender3D.h.
Referenced by createVectorPlanes(), and initRenderPlane().
vt4
vmath::Vector2f vmtkRender3D::vt4 private
Definition at line 266 of file vmtkRender3D.h.
Referenced by createVectorPlanes(), and initRenderPlane().
The documentation for this class was generated from the following files:
C:/vmtk_Multi-volume_Raycasting/include/vmtkRender3D.h
C:/vmtk_Multi-volume_Raycasting/src/vmtkRender3D.cpp