VMTK: VMATH_NAMESPACE::Matrix4< T > Class Template Reference
VMATH_NAMESPACE::Matrix4< T > Class Template Reference
#include <vmath.h>
Public Member Functions
Matrix4 ()
Matrix4 (const T *dt)
Matrix4 (const T dt[4][4])
Matrix4 (const Matrix4< T > &src)
Matrix4 (Vector4< T > v[])
template<class FromT >
Matrix4 (const Matrix4< FromT > &src)
void identity ()
Vector4< T > vectorProductMatrix (const Vector4< T > &v) const
vectorProductMatrix: Multiplication function
bool operator== (const Matrix4< T > &rhs) const
bool operator!= (const Matrix4< T > &rhs) const
T & at (int x, int y)
const T & at (int x, int y) const
T & operator() (int i, int j)
const T & operator() (int i, int j) const
void setTranslation (const Vector3< T > &v)
void setTranslation (T nx, T ny, T nz)
Sets translation part of matrix.
Vector3< T > getTranslation () const
void setRotation (const Matrix3< T > &m)
Vector3< T > getScale () const
void setScale (T s)
void setScale (T sx, T sy, T sz)
void setScale (const Vector3< T > &s)
Matrix4< T > & operator= (const Matrix4< T > &rhs)
template<class FromT >
Matrix4< T > & operator= (const Matrix4< FromT > &rhs)
Matrix4< T > & operator= (const T *rhs)
Matrix4< T > operator+ (const Matrix4< T > &rhs) const
Matrix4< T > operator- (const Matrix4< T > &rhs) const
Matrix4< T > operator+ (T rhs) const
Matrix4< T > operator- (T rhs) const
Matrix4< T > operator* (T rhs) const
Matrix4< T > operator/ (T rhs) const
Vector4< T > operator* (const Vector4< T > &rhs) const
Vector3< T > operator* (const Vector3< T > &rhs) const
Matrix4< T > operator* (Matrix4< T > rhs) const
T det ()
Matrix4< T > inverse ()
Matrix4< T > transpose ()
Matrix4< T > lerp (T fact, const Matrix4< T > &rhs) const
operator T* ()
operator const T * () const
std::string toString () const
Static Public Member Functions
static Matrix4< T > createMat4FromMat3 (Matrix3< T > n)
createMat4FromMat3 Creates 4x4 Matrix from 3x3 Matrix (Homogeneous Matrix).
static Vector4< T > vectorProductMatrix (const Vector4< T > v, Matrix4< T > m)
vectorProductMatrix: Multiplication function
static Matrix4< T > createRotationAroundAxis (T xDeg, T yDeg, T zDeg)
static Vector3< T > getEulerAngles (Matrix4< T > R)
static Matrix4< T > createTranslation (T x, T y, T z, T w=1)
Creates translation matrix.
static Matrix4< T > createScale (T sx, T sy, T sz)
static Matrix4< T > createLookAt (const Vector3< T > &eyePos, const Vector3< T > &centerPos, const Vector3< T > &upDir)
static Matrix4< T > createFrustum (T left, T right, T bottom, T top, T zNear, T zFar)
static Matrix4< T > createOrtho (T left, T right, T bottom, T top, T zNear, T zFar)
static Matrix4< T > Perspective_vmath (T fovy, T aspect, T n, T f)
set up a perspective projection matrix
static Matrix4< T > Perspective (T verticalAngle, T aspectRatio, T nearPlane, T farPlane)
set up a perspective projection matrix
template<class FromT >
static Matrix4< T > fromRowMajorArray (const FromT *arr)
template<class FromT >
static Matrix4< T > fromColumnMajorArray (const FromT *arr)
Public Attributes
T data [16]
Data stored in column major order.
Friends
std::ostream & operator<< (std::ostream &lhs, const Matrix4< T > &rhs)
Detailed Description
template<class T>
class VMATH_NAMESPACE::Matrix4< T >
Class for matrix 4x4
Note
Data stored in this matrix are in column major order. This arrangement suits OpenGL. If you're using row major matrix, consider using fromRowMajorArray as way for construction Matrix4<T> instance.
Definition at line 2321 of file vmath.h.
Constructor & Destructor Documentation
Matrix4() [1/6]
template<class T> VMATH_NAMESPACE::Matrix4< T >::Matrix4 () inline
Creates identity matrix
Definition at line 2331 of file vmath.h.
     {
         for (int i = 0; i < 16; i++)
             data[i] = (i % 5) ? 0 : 1;
     }
Matrix4() [2/6]
template<class T> VMATH_NAMESPACE::Matrix4< T >::Matrix4 (const T * dt) inline
Copy matrix values from array (these data must be in column major order!)
Definition at line 2341 of file vmath.h.
     {
         std::memcpy(data, dt, sizeof(T) * 16);
     }
Matrix4() [3/6]
template<class T> VMATH_NAMESPACE::Matrix4< T >::Matrix4 (const T dt[4][4]) inline
Copy matrix values from bidimensional array.
Definition at line 2349 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at().
     {
         Matrix4 m;
         for(int i=0;i<4;i++){
             for(int j=0;j<4;j++){
               m.at(j,i)=dt[i][j];
             }
         }
         std::memcpy(data, dt, sizeof(T) * 16);
     }
Matrix4() [4/6]
template<class T> VMATH_NAMESPACE::Matrix4< T >::Matrix4 (const Matrix4< T > & src) inline
Copy matrix values from array. Copy constructor.
Parameters
src Data source for new created instance of Matrix4.
Definition at line 2375 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         std::memcpy(data, src.data, sizeof(T) * 16);
     }
Matrix4() [5/6]
template<class T> VMATH_NAMESPACE::Matrix4< T >::Matrix4 (Vector4< T > v[]) inline
Definition at line 2380 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at(), and VMATH_NAMESPACE::Matrix4< T >::data.
                               { //add
         Matrix4 m;
         for(int i=0;i<4;i++){
               m.at(i,0)=v[i].x;
               m.at(i,1)=v[i].y;
               m.at(i,2)=v[i].z;
               m.at(i,3)=v[i].w;
         }
          std::memcpy(data,m.data,sizeof(T)*16);
     }
Matrix4() [6/6]
template<class T> template<class FromT > VMATH_NAMESPACE::Matrix4< T >::Matrix4 (const Matrix4< FromT > & src) inline
Copy casting constructor.
Parameters
src Data source for new created instance of Matrix4.
Definition at line 2396 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         for (int i = 0; i < 16; i++)
         {
             data[i] = static_cast<T>(src.data[i]);
         }
     }
Member Function Documentation
at() [1/2]
template<class T> T& VMATH_NAMESPACE::Matrix4< T >::at (int x, int y) inline
Get reference to element at postion (x,y).
Parameters
x Number of column (0..3)
y Number of row (0..3)
Definition at line 2869 of file vmath.h.
References VMATH_NAMESPACE::Vector2< T >::y.
Referenced by VMATH_NAMESPACE::Matrix4< T >::createFrustum(), VMATH_NAMESPACE::Matrix4< T >::createLookAt(), VMATH_NAMESPACE::Matrix4< T >::createMat4FromMat3(), VMATH_NAMESPACE::Matrix4< T >::createOrtho(), VMATH_NAMESPACE::Matrix4< T >::createRotationAroundAxis(), VMATH_NAMESPACE::Matrix4< T >::createScale(), VMATH_NAMESPACE::Matrix4< T >::createTranslation(), VMATH_NAMESPACE::Matrix4< T >::getEulerAngles(), VMATH_NAMESPACE::Matrix4< T >::inverse(), VMATH_NAMESPACE::Matrix4< T >::Matrix4(), VMATH_NAMESPACE::Matrix4< T >::operator*(), VMATH_NAMESPACE::Matrix4< T >::Perspective(), VMATH_NAMESPACE::Quaternion< T >::transform(), VMATH_NAMESPACE::Matrix4< T >::transpose(), and VMATH_NAMESPACE::Matrix4< T >::vectorProductMatrix().
     {
         assert(x >= 0 && x < 4);
         assert(y >= 0 && y < 4);
         return data[x * 4 + y];
     }
at() [2/2]
template<class T> const T& VMATH_NAMESPACE::Matrix4< T >::at (int x, int y) const inline
Get constant reference to element at position (x,y).
Parameters
x Number of column (0..3)
y Number of row (0..3)
Definition at line 2881 of file vmath.h.
References VMATH_NAMESPACE::Vector2< T >::y.
     {
         assert(x >= 0 && x < 4);
         assert(y >= 0 && y < 4);
         return data[x * 4 + y];
     }
createFrustum()
template<class T> static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::createFrustum (T left, T right, T bottom, T top, T zNear, T zFar) inline static
Creates OpenGL compatible perspective projection according specified frustum parameters.
Parameters
left Specify the coordinate for the left vertical clipping plane,
right Specify the coordinate for the right vertical clipping plane.
bottom Specify the coordinate for the bottom horizontal clipping plane,
top Specify the coordinate for the top horizontal clipping plane.
zNear Specify the distance to the near clipping plane. Distance must be positive.
zFar Specify the distance to the far depth clipping plane. Distance must be positive.
Returns
Projection matrix for specified frustum.
Definition at line 2633 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at().
     {
         /*
          *
           2 zNear
         ------------       0              A              0
         right - left
                         2 zNear
             0         ------------        B              0
                       top - bottom
             0              0              C              D
             0              0              -1             0
                                                      A = (right + left) / (right - left)
                                                      B = (top + bottom) / (top - bottom)
                                                     C = - (zFar + zNear) / (zFar - zNear)
                                                     D = - (2 zFar zNear) / (zFar - zNear)
          *
          */
         Matrix4<T> ret;
         const T invWidth = 1.0 / (right - left);
         const T invHeight = 1.0 / (top - bottom);
         const T invDepth = 1.0 / (zFar - zNear);
         const T twoZNear = 2 * zNear;
         ret.at(0,0) = twoZNear * invWidth;
         ret.at(1,1) = twoZNear * invHeight;
         ret.at(2,0) = (right + left) * invWidth;
         ret.at(2,1) = (top + bottom) * invHeight;
         ret.at(2,2) = - (zFar + zNear) * invDepth;
         ret.at(2,3) = -1;
         ret.at(3,2) = - twoZNear * zFar * invDepth;
         return ret;
     }
createLookAt()
template<class T> static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::createLookAt (const Vector3< T > & eyePos, const Vector3< T > & centerPos, const Vector3< T > & upDir) inline static
Creates new view matrix to look from specified position eyePos to specified position centerPos
Parameters
eyePos A position of camera
centerPos A position where camera looks-at
upDir Direction of up vector
Returns
Resulting view matrix that looks from and at specific position.
Definition at line 2587 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at(), VMATH_NAMESPACE::Matrix4< T >::createTranslation(), VMATH_NAMESPACE::Vector3< T >::crossProduct(), VMATH_NAMESPACE::Vector3< T >::normalize(), VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
     {
         Vector3<T> forward, side, up;
         Matrix4<T> m;
         forward = centerPos - eyePos;
         up = upDir;
         forward.normalize();
         // Side = forward x up
         side = forward.crossProduct(up);
         side.normalize();
         // Recompute up as: up = side x forward
         up = side.crossProduct(forward);
         m.at(0, 0) = side.x;
         m.at(1, 0) = side.y;
         m.at(2, 0) = side.z;
         m.at(0, 1) = up.x;
         m.at(1, 1) = up.y;
         m.at(2, 1) = up.z;
         m.at(0, 2) = -forward.x;
         m.at(1, 2) = -forward.y;
         m.at(2, 2) = -forward.z;
         m = m * Matrix4<T>::createTranslation(-eyePos.x, -eyePos.y, -eyePos.z);
         return m;
     }
createMat4FromMat3()
template<class T> static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::createMat4FromMat3 (Matrix3< T > n) inline static
createMat4FromMat3 Creates 4x4 Matrix from 3x3 Matrix (Homogeneous Matrix).
Parameters
n 3x3 Matrix.
Returns
m: 4x4 Matrix.
Definition at line 2421 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::at(), and VMATH_NAMESPACE::Matrix4< T >::at().
     {
        Matrix4<T> m;
        m.at(0,0)= n.at(0,0); m.at(1,0)= n.at(1,0); m.at(2,0)= n.at(2,0); m.at(3,0)= 0.0f;
        m.at(0,1)= n.at(0,1); m.at(1,1)= n.at(1,1); m.at(2,1)= n.at(2,1); m.at(3,1)= 0.0f;
        m.at(0,2)= n.at(0,2); m.at(1,2)= n.at(1,2); m.at(2,2)= n.at(2,2); m.at(3,2)= 0.0f;
        m.at(0,3)= 0.0f;      m.at(1,3)= 0.0f;      m.at(2,3)= 0.0f;      m.at(3,3)= 1.0f;
        return m;
     }
createOrtho()
template<class T> static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::createOrtho (T left, T right, T bottom, T top, T zNear, T zFar) inline static
Creates OpenGL compatible orthographic projection matrix.
Parameters
left Specify the coordinate for the left vertical clipping plane,
right Specify the coordinate for the right vertical clipping plane.
bottom Specify the coordinate for the bottom horizontal clipping plane,
top Specify the coordinate for the top horizontal clipping plane.
zNear Specify the distance to the nearer depth clipping plane. This value is negative if the plane is to be behind the viewer,
zFar Specify the distance to the farther depth clipping plane. This value is negative if the plane is to be behind the viewer.
Returns
Othrographic projection matrix.
Definition at line 2691 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at().
     {
         /*
                2
         ------------       0              0              tx
         right - left
                            2
             0         ------------        0              ty
                       top - bottom
                                           -2
             0              0         ------------        tz
                                       zFar-zNear
             0              0              0              1
        where
                                                     tx = - (right + left) / (right - left)
                                                     ty = - (top + bottom) / (top - bottom)
                                                     tz = - (zFar + zNear) / (zFar - zNear)
          */
         const T invWidth = 1.0 / (right  - left);
         const T invHeight = 1.0 / (top - bottom);
         const T invDepth = 1.0 / (zFar - zNear);
         Matrix4<T> ret;
         ret.at(0,0) = 2 * invWidth;
         ret.at(1,1) = 2 * invHeight;
         ret.at(2,2) = -2 * invDepth;
         ret.at(3,0) = -(right + left) * invWidth;
         ret.at(3,1) = -(top + bottom) * invHeight;
         ret.at(3,2) = -(zFar + zNear) * invDepth;
         return ret;
     }
createRotationAroundAxis()
template<class T> static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::createRotationAroundAxis (T xDeg, T yDeg, T zDeg) inline static
Creates rotation matrix by rotation around axis.
Parameters
xDeg Angle (in degrees) of rotation around axis X.
yDeg Angle (in degrees) of rotation around axis Y.
zDeg Angle (in degrees) of rotation around axis Z.
Definition at line 2470 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at(), and DEG2RAD.
     {
         T xRads(DEG2RAD(xDeg));
         T yRads(DEG2RAD(yDeg));
         T zRads(DEG2RAD(zDeg));
         Matrix4<T> ma, mb, mc;
         float ac = cos(xRads);
         float as = sin(xRads);
         float bc = cos(yRads);
         float bs = sin(yRads);
         float cc = cos(zRads);
         float cs = sin(zRads);
         ma.at(1, 1) = ac;
         ma.at(2, 1) = as;
         ma.at(1, 2) = -as;
         ma.at(2, 2) = ac;
         mb.at(0, 0) = bc;
         mb.at(2, 0) = -bs;
         mb.at(0, 2) = bs;
         mb.at(2, 2) = bc;
         mc.at(0, 0) = cc;
         mc.at(1, 0) = cs;
         mc.at(0, 1) = -cs;
         mc.at(1, 1) = cc;
         /*std::cout << "RotVec = " << a << "," << b << "," << c << std::endl;
          std::cout << "Rx = " << std::endl << ma;
          std::cout << "Ry = " << std::endl << mb;
          std::cout << "Rz = " << std::endl << mc;*/
         Matrix4<T> ret = ma * mb * mc;
         //std::cout << "Result = " << std::endl << ma * (mb * mc);
         return ret;
     }
createScale()
template<class T> static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::createScale (T sx, T sy, T sz) inline static
Create scale matrix with sx, sy, and sz being values of matrix main diagonal.
Parameters
sx Scale in X-axis
sy Scale in Y-axis
sz Scale in Z-axis
Returns
Transform matrix 4x4 with scale transformation.
Definition at line 2570 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at().
     {
         Matrix4<T> ret;
         ret.at(0,0) = sx;
         ret.at(1,1) = sy;
         ret.at(2,2) = sz;
         return ret;
     }
createTranslation()
template<class T> static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::createTranslation (T x, T y, T z, T w = 1) inline static
Creates translation matrix.
Creates translation matrix.
Parameters
x X-direction translation
y Y-direction translation
z Z-direction translation
w for W-coordinate translation (implicitly set to 1)
Definition at line 2551 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at(), VMATH_NAMESPACE::Vector2< T >::x, and VMATH_NAMESPACE::Vector2< T >::y.
Referenced by VMATH_NAMESPACE::Matrix4< T >::createLookAt().
     {
         Matrix4 ret;
         ret.at(3, 0) = x;
         ret.at(3, 1) = y;
         ret.at(3, 2) = z;
         ret.at(3, 3) = w;
         return ret;
     }
det()
template<class T> T VMATH_NAMESPACE::Matrix4< T >::det () inline
Computes determinant of matrix
Returns
Determinant of matrix
Note
This function does 3 * 4 * 6 muls, 3 * 6 adds.
Definition at line 3167 of file vmath.h.
     {
         return +at(3, 0) * at(2, 1) * at(1, 2) * at(0, 3) - at(2, 0) * at(3, 1) * at(1, 2) * at(0, 3)
                 - at(3, 0) * at(1, 1) * at(2, 2) * at(0, 3) + at(1, 0) * at(3, 1) * at(2, 2) * at(0, 3)
         + at(2, 0) * at(1, 1) * at(3, 2) * at(0, 3) - at(1, 0) * at(2, 1) * at(3, 2) * at(0, 3)
                 - at(3, 0) * at(2, 1) * at(0, 2) * at(1, 3) + at(2, 0) * at(3, 1) * at(0, 2) * at(1, 3)
         + at(3, 0) * at(0, 1) * at(2, 2) * at(1, 3) - at(0, 0) * at(3, 1) * at(2, 2) * at(1, 3)
                 - at(2, 0) * at(0, 1) * at(3, 2) * at(1, 3) + at(0, 0) * at(2, 1) * at(3, 2) * at(1, 3)
         + at(3, 0) * at(1, 1) * at(0, 2) * at(2, 3) - at(1, 0) * at(3, 1) * at(0, 2) * at(2, 3)
                 - at(3, 0) * at(0, 1) * at(1, 2) * at(2, 3) + at(0, 0) * at(3, 1) * at(1, 2) * at(2, 3)
         + at(1, 0) * at(0, 1) * at(3, 2) * at(2, 3) - at(0, 0) * at(1, 1) * at(3, 2) * at(2, 3)
                 - at(2, 0) * at(1, 1) * at(0, 2) * at(3, 3) + at(1, 0) * at(2, 1) * at(0, 2) * at(3, 3)
         + at(2, 0) * at(0, 1) * at(1, 2) * at(3, 3) - at(0, 0) * at(2, 1) * at(1, 2) * at(3, 3)
                 - at(1, 0) * at(0, 1) * at(2, 2) * at(3, 3) + at(0, 0) * at(1, 1) * at(2, 2) * at(3, 3);
     }
fromColumnMajorArray()
template<class T> template<class FromT > static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::fromColumnMajorArray (const FromT * arr) inline static
Creates new matrix 4x4 from array that represents such matrix 4x4 as array of tightly packed elements in column major order.
Parameters
arr An array of elements for 4x4 matrix in column major order.
Returns
An instance of Matrix4<T> representing arr
Definition at line 2822 of file vmath.h.
     {
         const T retData[] =
         { static_cast<T>(arr[0]), static_cast<T>(arr[1]), static_cast<T>(arr[2]), static_cast<T>(arr[3]),
                 static_cast<T>(arr[4]), static_cast<T>(arr[5]), static_cast<T>(arr[6]), static_cast<T>(arr[7]),
                 static_cast<T>(arr[8]), static_cast<T>(arr[9]), static_cast<T>(arr[10]), static_cast<T>(arr[11]),
                 static_cast<T>(arr[12]), static_cast<T>(arr[13]), static_cast<T>(arr[14]), static_cast<T>(arr[15]) };
         return retData;
     }
fromRowMajorArray()
template<class T> template<class FromT > static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::fromRowMajorArray (const FromT * arr) inline static
Creates new matrix 4x4 from array that represents such matrix 4x4 as array of tightly packed elements in row major order.
Parameters
arr An array of elements for 4x4 matrix in row major order.
Returns
An instance of Matrix4<T> representing arr
Definition at line 2804 of file vmath.h.
     {
         const T retData[] =
         { static_cast<T>(arr[0]), static_cast<T>(arr[4]), static_cast<T>(arr[8]), static_cast<T>(arr[12]),
                 static_cast<T>(arr[1]), static_cast<T>(arr[5]), static_cast<T>(arr[9]), static_cast<T>(arr[13]),
                 static_cast<T>(arr[2]), static_cast<T>(arr[6]), static_cast<T>(arr[10]), static_cast<T>(arr[14]),
                 static_cast<T>(arr[3]), static_cast<T>(arr[7]), static_cast<T>(arr[11]), static_cast<T>(arr[15]) };
         return retData;
     }
getEulerAngles()
template<class T> static Vector3<T> VMATH_NAMESPACE::Matrix4< T >::getEulerAngles (Matrix4< T > R) inline static
Definition at line 2510 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at(), VMATH_NAMESPACE::closeEnough(), M_PI, VMATH_NAMESPACE::Vector2< T >::x, and VMATH_NAMESPACE::Vector2< T >::y.
{
         //check for gimbal lock
         if (closeEnough(R.at(2,0), -1.0f)) {
             float x = 0; //gimbal lock, value of x doesn't matter
             float y = M_PI / 2;
             float z = x + atan2(R.at(0,1), R.at(0,2));
             return Vector3<T>(x, y, z);
         } else if (closeEnough(R.at(2,0), 1.0f)) {
             float x = 0;
             float y = -M_PI / 2;
             float z = -x + atan2(-R.at(0,1), -R.at(0,2));
             return Vector3<T>(x, y, z);
         } else { //two solutions exist
             float x1 = -asin(R.at(2,0));
             float x2 = M_PI - x1;
             float y1 = atan2(R.at(2,1) / cos(x1), R.at(2,2) / cos(x1));
             float y2 = atan2(R.at(2,1) / cos(x2), R.at(2,2) / cos(x2));
             float z1 = atan2(R.at(1,0) / cos(x1), R.at(0,0) / cos(x1));
             float z2 = atan2(R.at(1,0) / cos(x2), R.at(0,0) / cos(x2));
             //choose one solution to return
             //for example the "shortest" rotation
             if ((std::abs(x1) + std::abs(y1) + std::abs(z1)) <= (std::abs(x2) + std::abs(y2) + std::abs(z2))) {
                 return Vector3<T>(x1, y1, z1);
             } else {
                 return Vector3<T>(x2, y2, z2);
             }
         }
     }
getScale()
template<class T> Vector3<T> VMATH_NAMESPACE::Matrix4< T >::getScale () const inline
Gets matrix scale
Returns
Scales (i.e. first three values from matrix diagonal.
Definition at line 2964 of file vmath.h.
     { return Vector3<T>(at(0,0), at(1,1), at(2,2)); }
getTranslation()
template<class T> Vector3<T> VMATH_NAMESPACE::Matrix4< T >::getTranslation () const inline
Definition at line 2939 of file vmath.h.
     {
         return Vector3<T>(at(3, 0), at(3, 1), at(3, 2));
     }
identity()
template<class T> void VMATH_NAMESPACE::Matrix4< T >::identity () inline
Resets matrix to be identity matrix
Definition at line 2409 of file vmath.h.
     {
         for (int i = 0; i < 16; i++)
             data[i] = (i % 5) ? 0 : 1;
     }
inverse()
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::inverse () inline
Computes inverse matrix
Returns
Inverse matrix of this matrix.
Note
This is a little bit time consuming operation (16 * 6 * 3 muls, 16 * 5 adds + det() + mul() functions)
Definition at line 3196 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at().
     {
         Matrix4<T> ret;
         ret.at(0, 0) = +at(2, 1) * at(3, 2) * at(1, 3) - at(3, 1) * at(2, 2) * at(1, 3) + at(3, 1) * at(1, 2) * at(2, 3)
                 - at(1, 1) * at(3, 2) * at(2, 3) - at(2, 1) * at(1, 2) * at(3, 3) + at(1, 1) * at(2, 2) * at(3, 3);
         ret.at(1, 0) = +at(3, 0) * at(2, 2) * at(1, 3) - at(2, 0) * at(3, 2) * at(1, 3) - at(3, 0) * at(1, 2) * at(2, 3)
                 + at(1, 0) * at(3, 2) * at(2, 3) + at(2, 0) * at(1, 2) * at(3, 3) - at(1, 0) * at(2, 2) * at(3, 3);
         ret.at(2, 0) = +at(2, 0) * at(3, 1) * at(1, 3) - at(3, 0) * at(2, 1) * at(1, 3) + at(3, 0) * at(1, 1) * at(2, 3)
                 - at(1, 0) * at(3, 1) * at(2, 3) - at(2, 0) * at(1, 1) * at(3, 3) + at(1, 0) * at(2, 1) * at(3, 3);
         ret.at(3, 0) = +at(3, 0) * at(2, 1) * at(1, 2) - at(2, 0) * at(3, 1) * at(1, 2) - at(3, 0) * at(1, 1) * at(2, 2)
                 + at(1, 0) * at(3, 1) * at(2, 2) + at(2, 0) * at(1, 1) * at(3, 2) - at(1, 0) * at(2, 1) * at(3, 2);
         ret.at(0, 1) = +at(3, 1) * at(2, 2) * at(0, 3) - at(2, 1) * at(3, 2) * at(0, 3) - at(3, 1) * at(0, 2) * at(2, 3)
                 + at(0, 1) * at(3, 2) * at(2, 3) + at(2, 1) * at(0, 2) * at(3, 3) - at(0, 1) * at(2, 2) * at(3, 3);
         ret.at(1, 1) = +at(2, 0) * at(3, 2) * at(0, 3) - at(3, 0) * at(2, 2) * at(0, 3) + at(3, 0) * at(0, 2) * at(2, 3)
                 - at(0, 0) * at(3, 2) * at(2, 3) - at(2, 0) * at(0, 2) * at(3, 3) + at(0, 0) * at(2, 2) * at(3, 3);
         ret.at(2, 1) = +at(3, 0) * at(2, 1) * at(0, 3) - at(2, 0) * at(3, 1) * at(0, 3) - at(3, 0) * at(0, 1) * at(2, 3)
                 + at(0, 0) * at(3, 1) * at(2, 3) + at(2, 0) * at(0, 1) * at(3, 3) - at(0, 0) * at(2, 1) * at(3, 3);
         ret.at(3, 1) = +at(2, 0) * at(3, 1) * at(0, 2) - at(3, 0) * at(2, 1) * at(0, 2) + at(3, 0) * at(0, 1) * at(2, 2)
                 - at(0, 0) * at(3, 1) * at(2, 2) - at(2, 0) * at(0, 1) * at(3, 2) + at(0, 0) * at(2, 1) * at(3, 2);
         ret.at(0, 2) = +at(1, 1) * at(3, 2) * at(0, 3) - at(3, 1) * at(1, 2) * at(0, 3) + at(3, 1) * at(0, 2) * at(1, 3)
                 - at(0, 1) * at(3, 2) * at(1, 3) - at(1, 1) * at(0, 2) * at(3, 3) + at(0, 1) * at(1, 2) * at(3, 3);
         ret.at(1, 2) = +at(3, 0) * at(1, 2) * at(0, 3) - at(1, 0) * at(3, 2) * at(0, 3) - at(3, 0) * at(0, 2) * at(1, 3)
                 + at(0, 0) * at(3, 2) * at(1, 3) + at(1, 0) * at(0, 2) * at(3, 3) - at(0, 0) * at(1, 2) * at(3, 3);
         ret.at(2, 2) = +at(1, 0) * at(3, 1) * at(0, 3) - at(3, 0) * at(1, 1) * at(0, 3) + at(3, 0) * at(0, 1) * at(1, 3)
                 - at(0, 0) * at(3, 1) * at(1, 3) - at(1, 0) * at(0, 1) * at(3, 3) + at(0, 0) * at(1, 1) * at(3, 3);
         ret.at(3, 2) = +at(3, 0) * at(1, 1) * at(0, 2) - at(1, 0) * at(3, 1) * at(0, 2) - at(3, 0) * at(0, 1) * at(1, 2)
                 + at(0, 0) * at(3, 1) * at(1, 2) + at(1, 0) * at(0, 1) * at(3, 2) - at(0, 0) * at(1, 1) * at(3, 2);
         ret.at(0, 3) = +at(2, 1) * at(1, 2) * at(0, 3) - at(1, 1) * at(2, 2) * at(0, 3) - at(2, 1) * at(0, 2) * at(1, 3)
                 + at(0, 1) * at(2, 2) * at(1, 3) + at(1, 1) * at(0, 2) * at(2, 3) - at(0, 1) * at(1, 2) * at(2, 3);
         ret.at(1, 3) = +at(1, 0) * at(2, 2) * at(0, 3) - at(2, 0) * at(1, 2) * at(0, 3) + at(2, 0) * at(0, 2) * at(1, 3)
                 - at(0, 0) * at(2, 2) * at(1, 3) - at(1, 0) * at(0, 2) * at(2, 3) + at(0, 0) * at(1, 2) * at(2, 3);
         ret.at(2, 3) = +at(2, 0) * at(1, 1) * at(0, 3) - at(1, 0) * at(2, 1) * at(0, 3) - at(2, 0) * at(0, 1) * at(1, 3)
                 + at(0, 0) * at(2, 1) * at(1, 3) + at(1, 0) * at(0, 1) * at(2, 3) - at(0, 0) * at(1, 1) * at(2, 3);
         ret.at(3, 3) = +at(1, 0) * at(2, 1) * at(0, 2) - at(2, 0) * at(1, 1) * at(0, 2) + at(2, 0) * at(0, 1) * at(1, 2)
                 - at(0, 0) * at(2, 1) * at(1, 2) - at(1, 0) * at(0, 1) * at(2, 2) + at(0, 0) * at(1, 1) * at(2, 2);
         return ret / det();
     }
lerp()
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::lerp (T fact, const Matrix4< T > & rhs) const inline
Linear interpolation of two matrices
Parameters
fact Factor of interpolation. For translation from positon of this matrix (lhs) to matrix rhs, values of factor goes from 0.0 to 1.0.
rhs Second Matrix for interpolation
Note
However values of fact parameter are reasonable only in interval [0.0 , 1.0], you can pass also values outside of this interval and you can get result (extrapolation?)
Definition at line 3276 of file vmath.h.
     {
         Matrix4<T> ret = (*this) + (rhs - (*this)) * fact;
         return ret;
     }
operator const T *()
template<class T> VMATH_NAMESPACE::Matrix4< T >::operator const T * () const inline
Conversion to pointer operator
Returns
Constant Pointer to internally stored (in management of class Matrix4<T>) used for passing Matrix4<T> values to gl*[fd]v functions.
Definition at line 3298 of file vmath.h.
     {
         return (const T*) data;
     }
operator T*()
template<class T> VMATH_NAMESPACE::Matrix4< T >::operator T* () inline
Conversion to pointer operator
Returns
Pointer to internally stored (in management of class Matrix4<T>) used for passing Matrix4<T> values to gl*[fd]v functions.
Definition at line 3288 of file vmath.h.
     {
         return (T*) data;
     }
operator!=()
template<class T> bool VMATH_NAMESPACE::Matrix4< T >::operator!= (const Matrix4< T > & rhs) const inline
Inequality test operator
Parameters
rhs Right hand side argument of binary operator.
Returns
not (lhs == rhs) :-P
Definition at line 2858 of file vmath.h.
     {
         return !(*this == rhs);
     }
operator()() [1/2]
template<class T> T& VMATH_NAMESPACE::Matrix4< T >::operator() (int i, int j) inline
Get reference to element at position (i,j), with math matrix notation
Parameters
i Number of row (1..4)
j Number of column (1..4)
Definition at line 2893 of file vmath.h.
     {
         assert(i >= 1 && i <= 4);
         assert(j >= 1 && j <= 4);
         return data[(j - 1) * 4 + i - 1];
     }
operator()() [2/2]
template<class T> const T& VMATH_NAMESPACE::Matrix4< T >::operator() (int i, int j) const inline
Get constant reference to element at position (i,j), with math matrix notation
Parameters
i Number of row (1..4)
j Number of column (1..4)
Definition at line 2905 of file vmath.h.
     {
         assert(i >= 1 && i <= 4);
         assert(j >= 1 && j <= 4);
         return data[(j - 1) * 4 + i - 1];
     }
operator*() [1/4]
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::operator* (T rhs) const inline
Multiplication operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3094 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         Matrix4<T> ret;
         for (int i = 0; i < 16; i++)
             ret.data[i] = data[i] * rhs;
         return ret;
     }
operator*() [2/4]
template<class T> Vector4<T> VMATH_NAMESPACE::Matrix4< T >::operator* (const Vector4< T > & rhs) const inline
Multiplication operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3119 of file vmath.h.
References VMATH_NAMESPACE::Vector4< T >::w, VMATH_NAMESPACE::Vector4< T >::x, VMATH_NAMESPACE::Vector4< T >::y, and VMATH_NAMESPACE::Vector4< T >::z.
     {
         return Vector4<T>(data[0] * rhs.x + data[4] * rhs.y + data[8] * rhs.z + data[12] * rhs.w,
                 data[1] * rhs.x + data[5] * rhs.y + data[9] * rhs.z + data[13] * rhs.w,
                 data[2] * rhs.x + data[6] * rhs.y + data[10] * rhs.z + data[14] * rhs.w,
                 data[3] * rhs.x + data[7] * rhs.y + data[11] * rhs.z + data[15] * rhs.w);
     }
operator*() [3/4]
template<class T> Vector3<T> VMATH_NAMESPACE::Matrix4< T >::operator* (const Vector3< T > & rhs) const inline
Multiplication operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3132 of file vmath.h.
References VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
     {
         return Vector3<T>(data[0] * rhs.x + data[4] * rhs.y + data[8] * rhs.z,
                 data[1] * rhs.x + data[5] * rhs.y + data[9] * rhs.z,
                 data[2] * rhs.x + data[6] * rhs.y + data[10] * rhs.z);
     }
operator*() [4/4]
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::operator* (Matrix4< T > rhs) const inline
Multiplication operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3143 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at().
     {
         static Matrix4<T> w;
         for (int i = 0; i < 4; i++)
         {
             for (int j = 0; j < 4; j++)
             {
                 T n = 0;
                 for (int k = 0; k < 4; k++)
                     n += rhs.at(i, k) * at(k, j);
                 w.at(i, j) = n;
             }
         }
         return w;
     }
operator+() [1/2]
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::operator+ (const Matrix4< T > & rhs) const inline
Addition operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3045 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         Matrix4<T> ret;
         for (int i = 0; i < 16; i++)
             ret.data[i] = data[i] + rhs.data[i];
         return ret;
     }
operator+() [2/2]
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::operator+ (T rhs) const inline
Addition operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3070 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         Matrix4<T> ret;
         for (int i = 0; i < 16; i++)
             ret.data[i] = data[i] + rhs;
         return ret;
     }
operator-() [1/2]
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::operator- (const Matrix4< T > & rhs) const inline
Subtraction operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3057 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         Matrix4<T> ret;
         for (int i = 0; i < 16; i++)
             ret.data[i] = data[i] - rhs.data[i];
         return ret;
     }
operator-() [2/2]
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::operator- (T rhs) const inline
Subtraction operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3082 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         Matrix4<T> ret;
         for (int i = 0; i < 16; i++)
             ret.data[i] = data[i] - rhs;
         return ret;
     }
operator/()
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::operator/ (T rhs) const inline
Division operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3106 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         Matrix4<T> ret;
         for (int i = 0; i < 16; i++)
             ret.data[i] = data[i] / rhs;
         return ret;
     }
operator=() [1/3]
template<class T> Matrix4<T>& VMATH_NAMESPACE::Matrix4< T >::operator= (const Matrix4< T > & rhs) inline
Copy operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3004 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         std::memcpy(data, rhs.data, sizeof(T) * 16);
         return *this;
     }
operator=() [2/3]
template<class T> template<class FromT > Matrix4<T>& VMATH_NAMESPACE::Matrix4< T >::operator= (const Matrix4< FromT > & rhs) inline
Copy casting operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3015 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data.
     {
         for (int i = 0; i < 16; i++)
         {
             data[i] = static_cast<T>(rhs.data[i]);
         }
         return *this;
     }
operator=() [3/3]
template<class T> Matrix4<T>& VMATH_NAMESPACE::Matrix4< T >::operator= (const T * rhs) inline
Copy operator
Parameters
rhs Right hand side argument of binary operator.
Definition at line 3028 of file vmath.h.
     {
         std::memcpy(data, rhs, sizeof(T) * 16);
         return *this;
     }
operator==()
template<class T> bool VMATH_NAMESPACE::Matrix4< T >::operator== (const Matrix4< T > & rhs) const inline
Equality test operator
Parameters
rhs Right hand side argument of binary operator.
Note
Test of equality is based of threshold EPSILON value. To be two values equal, must satisfy this condition all elements of matrix | lhs[i] - rhs[i] | < EPSILON, same for y-coordinate, z-coordinate, and w-coordinate.
Definition at line 2842 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::data, and EPSILON.
     {
         for (int i = 0; i < 16; i++)
         {
             if (std::fabs(data[i] - rhs.data[i]) >= EPSILON
                 )
                 return false;
         }
         return true;
     }
Perspective()
template<class T> static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::Perspective (T verticalAngle, T aspectRatio, T nearPlane, T farPlane) inline static
set up a perspective projection matrix
Parameters
[in] verticalAngle field of view angle, in degrees, in the y direction
[in] aspectRatio ratio of x (width) and y (height)
[in] nearPlane near clipping plane distance from the viewer
[in] farPlane far clipping plane distance from the viewer
Returns
perspective projection matrix
Note
implemented by Jos Angel Ivan Rubianes Silva
Definition at line 2771 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at(), M_PI, and VMATH_NAMESPACE::radians().
     {
         Matrix4<T> ret;
         // Bail out if the projection volume is zero-sized.
         if (nearPlane == farPlane || aspectRatio == 0.0f)
             return ret;
         // Construct the projection.
         T radians = (verticalAngle / 2.0f) * M_PI / 180.0f;
         T sine = sin(radians);
         if (sine == 0.0f)
             return ret;
         T cotan = cos(radians) / sine;
         T clip = farPlane - nearPlane;
         ret.at(0,0) = cotan / aspectRatio;
         ret.at(1,1) = cotan;
         ret.at(2,2) = -(nearPlane + farPlane) / clip;
         ret.at(3,2) = -(2.0f * nearPlane * farPlane) / clip;
         ret.at(2,3) = -1.0f;
         ret.at(3,3) = 0.0f;
         return ret;
     }
Perspective_vmath()
template<class T> static Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::Perspective_vmath (T fovy, T aspect, T n, T f) inline static
set up a perspective projection matrix
Parameters
[in] fovy field of view angle, in degrees, in the y direction
[in] aspect ratio of x (width) to y (height)
[in] n near clipping plane distance from the viewer
[in] f far clipping plane distance fromn the viewer
Returns
perspective projection matrix
Note
from OpenGL redbook implementation (gluPerspective)
Definition at line 2745 of file vmath.h.
References VMATH_NAMESPACE::radians().
     {
          T q = 1.0f / tan(radians(0.5f * fovy));
          T A = q / aspect;
          T B = (n + f) / (n - f);
          T C = (2.0f * n * f) / (n - f);
         Vector4<T> result[4];
         result[0] = Vector4<T>(A, 0.0f, 0.0f, 0.0f);
         result[1] = Vector4<T>(0.0f, q, 0.0f, 0.0f);
         result[2] = Vector4<T>(0.0f, 0.0f, B, -1.0f);
         result[3] = Vector4<T>(0.0f, 0.0f, C, 0.0f);
         return Matrix4<T>(result);
     }
setRotation()
template<class T> void VMATH_NAMESPACE::Matrix4< T >::setRotation (const Matrix3< T > & m) inline
Sets rotation part (matrix 3x3) of matrix.
Parameters
m Rotation part of matrix
Definition at line 2949 of file vmath.h.
References VMATH_NAMESPACE::Matrix3< T >::at().
     {
         for (int i = 0; i < 3; i++)
         {
             for (int j = 0; j < 3; j++)
             {
                 at(i, j) = m.at(i, j);
             }
         }
     }
setScale() [1/3]
template<class T> void VMATH_NAMESPACE::Matrix4< T >::setScale (T s) inline
Sets matrix uniform scale values
Parameters
s Uniform scale value
Definition at line 2971 of file vmath.h.
References VMATH_NAMESPACE::Vector2< T >::s.
     {
         at(0,0) = at(1,1) = at(2,2) = s;
     }
setScale() [2/3]
template<class T> void VMATH_NAMESPACE::Matrix4< T >::setScale (T sx, T sy, T sz) inline
Sets matrix scale for all axes.
Parameters
sx X-axis scale factor
sy Y-axis scale factor
sz Z-axis scale factor
Definition at line 2982 of file vmath.h.
     {
         at(0,0) = sx;
         at(1,1) = sy;
         at(2,2) = sz;
     }
setScale() [3/3]
template<class T> void VMATH_NAMESPACE::Matrix4< T >::setScale (const Vector3< T > & s) inline
Sets matrix scale for all axes.
Parameters
s Scale factors for X, Y, and Z coordinate.
Definition at line 2993 of file vmath.h.
References VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
     {
         at(0,0) = s.x;
         at(1,1) = s.y;
         at(2,2) = s.z;
     }
setTranslation() [1/2]
template<class T> void VMATH_NAMESPACE::Matrix4< T >::setTranslation (const Vector3< T > & v) inline
Sets translation part of matrix.
Parameters
v Vector of translation to be set.
Definition at line 2917 of file vmath.h.
References VMATH_NAMESPACE::Vector3< T >::x, VMATH_NAMESPACE::Vector3< T >::y, and VMATH_NAMESPACE::Vector3< T >::z.
     {
         at(3, 0) = v.x;
         at(3, 1) = v.y;
         at(3, 2) = v.z;
         at(3, 3) = 1;
     }
setTranslation() [2/2]
template<class T> void VMATH_NAMESPACE::Matrix4< T >::setTranslation (T nx, T ny, T nz) inline
Sets translation part of matrix.
Parameters
nx X-axis element to be set.
ny Y-axis element to be set.
nz Z-axis element to be set.
Definition at line 2931 of file vmath.h.
     {
         at(3, 0) = nx;
         at(3, 1) = ny;
         at(3, 2) = nz;
         at(3, 3) = 1;
     }
toString()
template<class T> std::string VMATH_NAMESPACE::Matrix4< T >::toString () const inline
Gets string representation.
Definition at line 3327 of file vmath.h.
     {
         std::ostringstream oss;
         oss << *this;
         return oss.str();
     }
transpose()
template<class T> Matrix4<T> VMATH_NAMESPACE::Matrix4< T >::transpose () inline
Transpose matrix.
Definition at line 3254 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at().
     {
         Matrix4<T> ret;
         for (int i = 0; i < 4; i++)
         {
             for (int j = 0; j < 4; j++)
             {
                 ret.at(i, j) = at(j, i);
             }
         }
         return ret;
     }
vectorProductMatrix() [1/2]
template<class T> Vector4<T> VMATH_NAMESPACE::Matrix4< T >::vectorProductMatrix (const Vector4< T > & v) const inline
vectorProductMatrix: Multiplication function
Parameters
v vector4
Returns
v multiplied by currentMatrix (Matrix4)
Definition at line 2436 of file vmath.h.
     {
         Vector4<T> vxm;
         for(int i = 0; i < 4; i++){
             for(int j = 0; j < 4; j++){
                 vxm[i] += at(i,j) * v[j];
             }
         }
         return vxm;
     }
vectorProductMatrix() [2/2]
template<class T> static Vector4<T> VMATH_NAMESPACE::Matrix4< T >::vectorProductMatrix (const Vector4< T > v, Matrix4< T > m) inline static
vectorProductMatrix: Multiplication function
Parameters
v row vector4
m Matrix4
Returns
Vector4: v * m
Definition at line 2453 of file vmath.h.
References VMATH_NAMESPACE::Matrix4< T >::at().
     {
         Vector4<T> vxm;
         for(int i = 0; i < 4; i++){
             for(int j = 0; j < 4; j++){
                 vxm[i] += m.at(i,j) * v[j];
             }
         }
         return vxm;
     }
Friends And Related Function Documentation
operator<<
template<class T> std::ostream& operator<< (std::ostream & lhs, const Matrix4< T > & rhs) friend
Output to stream operator
Parameters
lhs Left hand side argument of operator (commonly ostream instance).
rhs Right hand side argument of operator.
Returns
Left hand side argument - the ostream object passed to operator.
Definition at line 3310 of file vmath.h.
     {
         for (int i = 0; i < 4; i++)
         {
             lhs << "|\t";
             for (int j = 0; j < 4; j++)
             {
                 lhs << rhs.at(j, i) << "\t";
             }
             lhs << "|" << std::endl;
         }
         return lhs;
     }
Member Data Documentation
data
template<class T> T VMATH_NAMESPACE::Matrix4< T >::data[16]
Data stored in column major order.
Definition at line 2325 of file vmath.h.
Referenced by VMATH_NAMESPACE::Matrix4< T >::Matrix4(), VMATH_NAMESPACE::Matrix4< T >::operator*(), VMATH_NAMESPACE::Matrix4< T >::operator+(), VMATH_NAMESPACE::Matrix4< T >::operator-(), VMATH_NAMESPACE::Matrix4< T >::operator/(), VMATH_NAMESPACE::Matrix4< T >::operator=(), and VMATH_NAMESPACE::Matrix4< T >::operator==().
The documentation for this class was generated from the following file:
C:/vmtk_Multi-volume_Raycasting/include/vmath.h