VMTK: C:/vmtk_Multi-volume_Raycasting/src/main_glsl_dvr.cpp File Reference
main_glsl_dvr.cpp File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <cstdio>
#include <cstring>
#include <string>
#include <iostream>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <math.h>
#include <GL/freeglut.h>
#include "vmtkRender3D.h"
Macros
#define FREEGLUT_STATIC
#define GLEW_STATIC
Functions
void init ()
initialize context OpenGL
void keyboard (unsigned char key, int x, int y)
keyboard callback function
void reshape (int w, int h)
void drawProxyGeometry ()
render the volume
void menu (int num)
int main (int argc, char *argv[])
Variables
static vmtkRender3D volumeRender
instance of the class vmtkRender3D for rendering the volume
static GLfloat spin_x =0.0
static GLfloat spin_y =0.0
static GLfloat spin_z =0.0
parameters for rotating the volume
static GLuint VIEWPORT_WIDTH =900
static GLuint VIEWPORT_HEIGHT =900
size of view the viewport
static int threshold = 23
initial threshold
static float blender =0.5f
initial blender
static int slice_x = 0
initial slice x
static int window
holds the name of the window created
static bool m_mprPreState = false
checks if the plane equation for multiplanar reformatting was provided
static bool m_mprState = false
checks if the plane equation for multiplanar reformatting is correct
Macro Definition Documentation
FREEGLUT_STATIC
#define FREEGLUT_STATIC
Definition at line 1 of file main_glsl_dvr.cpp.
GLEW_STATIC
#define GLEW_STATIC
Definition at line 4 of file main_glsl_dvr.cpp.
Function Documentation
drawProxyGeometry()
void drawProxyGeometry ()
render the volume
Definition at line 159 of file main_glsl_dvr.cpp.
References vmtkRender3D::render().
Referenced by main().
 {
     volumeRender.render();
     glutSwapBuffers();
     glutPostRedisplay();
 }
init()
void init ()
initialize context OpenGL
Definition at line 45 of file main_glsl_dvr.cpp.
References vmtkRender3D::initialize(), VIEWPORT_HEIGHT, and VIEWPORT_WIDTH.
Referenced by main().
 {
     volumeRender.initialize(VIEWPORT_WIDTH, VIEWPORT_HEIGHT);
 }
keyboard()
void keyboard (unsigned char key, int x, int y)
keyboard callback function
<< reset
<< increase threshold
<< decrease threshold
<< blender
Definition at line 52 of file main_glsl_dvr.cpp.
References blender, vmtkRender3D::getAcquisition(), vmtkRender3D::getMaxSliceLeft(), m_mprState, vmtkRender3D::setBlender(), vmtkRender3D::setClipLeftX(), vmtkRender3D::setEnableMPR(), vmtkRender3D::setRotation(), vmtkRender3D::setThreshold(), slice_x, spin_x, spin_y, spin_z, threshold, and Import::ImgFormat::umax.
Referenced by main().
 {
 switch (key) {
     case 'w':
     case 'W':
         spin_x += 5.0;
         volumeRender.setRotation(spin_x,spin_y,spin_z);
         break;
     case 's':
     case 'S':
         spin_x -= 5.0;
         volumeRender.setRotation(spin_x,spin_y,spin_z);
         break;
     case 'q':
     case 'Q':
         spin_y += 5.0;
         volumeRender.setRotation(spin_x,spin_y,spin_z);
         break;
     case 'e':
     case 'E':
         spin_y -= 5.0;
         volumeRender.setRotation(spin_x,spin_y,spin_z);
         break;
     case 'a':
     case 'A':
         spin_z += 5.0;
         volumeRender.setRotation(spin_x,spin_y,spin_z);
         break;
     case 'd':
     case 'D':
         spin_z -= 5.0;
         volumeRender.setRotation(spin_x,spin_y,spin_z);
         break;
     case 'r':
     case 'R':
         spin_x = spin_y = spin_z = 0.0;
         volumeRender.setRotation(spin_x,spin_y,spin_z);
         break;
     case '+':
         threshold += 1;
         if(threshold<=0){ threshold = 0; }
         if(threshold>=volumeRender.getAcquisition(0)->umax-1){ threshold = volumeRender.getAcquisition(0)->umax-1; }
         volumeRender.setThreshold(threshold);
         break;
     case '-':
         threshold -= 1;
         if(threshold<=0){ threshold = 0;}
         volumeRender.setThreshold(threshold);
         break;
     case 'b':
     case 'B':
         blender += 0.1;
         if (blender > 1.0){
             blender = 1.0;
         }
         volumeRender.setBlender(blender);
         break;
     case 'n':
     case 'N':
         blender -= 0.1;
         if (blender < 0.0){
             blender = 0.0;
         }
         volumeRender.setBlender(blender);
         break;
     case 'o':
     case 'O':
         slice_x++;
         if (slice_x > volumeRender.getMaxSliceLeft()){
             slice_x = volumeRender.getMaxSliceLeft();
         }
         volumeRender.setClipLeftX(slice_x);
         break;
     case 'p':
     case 'P':
         slice_x--;
         if (slice_x < 0){
             slice_x = 0;
         }
         volumeRender.setClipLeftX(slice_x);
         break;
     case '1':
         if(m_mprState){
             volumeRender.setEnableMPR(true);
         }
         break;
     case '2':
         if(m_mprState){
             volumeRender.setEnableMPR(false);
         }
         break;
     default:
         return;
     }
   glutPostRedisplay();
 }
main()
int main (int argc, char * argv[])
<<reading volumes
<<setting volumes acquisitions
<< reading plane equation for multiplanar reformatting
<< initialize OpenGL
<< set OpenGL context
<< initialize Glew
<< initialize context parameters
<< intialize window position
Definition at line 175 of file main_glsl_dvr.cpp.
References Import::DICOMImage(), drawProxyGeometry(), init(), keyboard(), m_mprPreState, m_mprState, nVolumes, vmtkRender3D::readMatrix(), vmtkRender3D::readPlane(), reshape(), vmtkRender3D::setAcquisition(), vmtkRender3D::setEnableMPR(), vmtkRender3D::setMPR(), vmtkRender3D::setStateMPRInput(), vmtkRender3D::setVectorInvMatrixReg(), Import::ImgFormat::umax, Import::ImgFormat::umin, VIEWPORT_HEIGHT, VIEWPORT_WIDTH, and window.
 {
     Import load;
     Import::ImgFormat *data;
     string *path;
     if( argc == 1 )
     {
         cerr << "Minimum usage: " << endl;
         cerr << argv[0] << " inputVolume1  inputVolume2 registeredMatrix" << endl;
         return EXIT_FAILURE;
     }
     int nParameters = argc-1;
     if( nParameters >12 ){
         cerr << "Too many parameters." << std::endl;
         cerr << "Maximum paramters usage: 12." << endl;
         return EXIT_FAILURE;
     }
     std::cout << "Numbers of parameters: " << nParameters << std::endl;
     int nVolumes=0;
     int nMatrices=0;
     if(nParameters%2==0){
         nVolumes = nParameters/2;
         nMatrices = nVolumes-1;
         std::cout << "Numbers of volumes for register: " << nVolumes <<std::endl;
         std::cout << "Numbers of matrices for register: " << nMatrices <<std::endl;
         std::cout << "With equation plane for multiplanar reformation." << std::endl;
         m_mprPreState = true;
     }
     else{
         nVolumes = (nParameters+1)/2;
         nMatrices = nVolumes-1;
         std::cout << "Numbers of volumes for register: " << nVolumes <<std::endl;
         std::cout << "Numbers of matrices for register: " << nMatrices <<std::endl;
         std::cout << "Without equation plane for multiplanar reformation." << std::endl;
         m_mprPreState = false;
     }
     data = new Import::ImgFormat[nVolumes];
     path = new string[nVolumes];
     std::vector<Import::ImgFormat*> acqVector;
     for(int i = 0; i< nVolumes; i++){
         path[i] = argv[i+1];
         data[i].umax = -pow(2,30);
         data[i].umin = pow(2,30);
         if (!load.DICOMImage (path[i], &data[i])) {
           std::cout << path[i] << "Cannot be imported!" << std::endl;
           return 0;
         }
         acqVector.push_back(&data[i]);
     }
     volumeRender.setAcquisition(acqVector);
     std::vector<vmath::Matrix4f> vectorInvMatrixReg;
     for(int i = 0; i< nMatrices; i++){
         vmath::Matrix4f imrv;
         if(!volumeRender.readMatrix(argv[i+1+nVolumes] ,imrv)){ return 0; }
         vectorInvMatrixReg.push_back(imrv);
     }
     volumeRender.setVectorInvMatrixReg(vectorInvMatrixReg);
     vmath::Vector4f eqp;
     if(m_mprPreState){
         if(!volumeRender.readPlane(argv[1+nVolumes+nMatrices], eqp) ){
             m_mprState=false; return 0;
         }
         m_mprState=true;
         volumeRender.setEnableMPR(false);
         volumeRender.setMPR(eqp);
     }
     else{
         m_mprState=false;
     }
     volumeRender.setStateMPRInput(m_mprState);
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_RGB | GLUT_DEPTH | GLUT_DOUBLE);
     window = glutCreateWindow("VMTK-SPS");
     std::cout << "OpenGL version supported by this platform: " << glGetString(GL_VERSION) << std::endl;
     glewInit();
     init();
     glutPositionWindow(10, 10);
     glutReshapeWindow(VIEWPORT_WIDTH, VIEWPORT_HEIGHT);
     glutReshapeFunc(reshape);
     glutDisplayFunc(drawProxyGeometry);
     glutKeyboardFunc(keyboard);
     glutMainLoop();
     return 0;
 }
menu()
void menu (int num)
Definition at line 167 of file main_glsl_dvr.cpp.
References window.
                   {
   if(num == 0){
     glutDestroyWindow(window);
     exit(0);
   }
   glutPostRedisplay();
  }
reshape()
void reshape (int w, int h)
Definition at line 151 of file main_glsl_dvr.cpp.
References vmtkRender3D::resize().
Referenced by main().
 {
     volumeRender.resize(w, h);
 }
Variable Documentation
blender
float blender =0.5f static
initial blender
Definition at line 36 of file main_glsl_dvr.cpp.
Referenced by keyboard(), and vmtkRender3D::setBlender().
m_mprPreState
bool m_mprPreState = false static
checks if the plane equation for multiplanar reformatting was provided
Definition at line 39 of file main_glsl_dvr.cpp.
Referenced by main().
m_mprState
bool m_mprState = false static
checks if the plane equation for multiplanar reformatting is correct
Definition at line 40 of file main_glsl_dvr.cpp.
Referenced by keyboard(), and main().
slice_x
int slice_x = 0 static
initial slice x
Definition at line 37 of file main_glsl_dvr.cpp.
Referenced by keyboard().
spin_x
GLfloat spin_x =0.0 static
Definition at line 33 of file main_glsl_dvr.cpp.
Referenced by keyboard().
spin_y
GLfloat spin_y =0.0 static
Definition at line 33 of file main_glsl_dvr.cpp.
Referenced by keyboard().
spin_z
GLfloat spin_z =0.0 static
parameters for rotating the volume
Definition at line 33 of file main_glsl_dvr.cpp.
Referenced by keyboard().
threshold
int threshold = 23 static
initial threshold
Definition at line 35 of file main_glsl_dvr.cpp.
Referenced by keyboard(), and vmtkRender3D::loadVolumesToTextures().
VIEWPORT_HEIGHT
GLuint VIEWPORT_HEIGHT =900 static
size of view the viewport
Definition at line 34 of file main_glsl_dvr.cpp.
Referenced by init(), and main().
VIEWPORT_WIDTH
GLuint VIEWPORT_WIDTH =900 static
Definition at line 34 of file main_glsl_dvr.cpp.
Referenced by init(), and main().
volumeRender
vmtkRender3D volumeRender static
instance of the class vmtkRender3D for rendering the volume
Definition at line 32 of file main_glsl_dvr.cpp.
window
int window static
holds the name of the window created
Definition at line 38 of file main_glsl_dvr.cpp.
Referenced by main(), and menu().