VMTK: std Namespace Reference
std Namespace Reference
Functions
template<typename T >
VEC2< T > min (const VEC2< T > &a, const VEC2< T > &b)
template<typename T >
VEC3< T > min (const VEC3< T > &a, const VEC3< T > &b)
template<typename T >
VEC4< T > min (const VEC4< T > &a, const VEC4< T > &b)
template<typename T >
VEC2< T > max (const VEC2< T > &a, const VEC2< T > &b)
template<typename T >
VEC3< T > max (const VEC3< T > &a, const VEC3< T > &b)
template<typename T >
VEC4< T > max (const VEC4< T > &a, const VEC4< T > &b)
Function Documentation
max() [1/3]
template<typename T > VEC2<T> std::max (const VEC2< T > & a, const VEC2< T > & b)
Gets vector containing maximal values of a and b coordinates.
Returns
Vector of maximal coordinates.
Definition at line 3969 of file vmath.h.
References max().
Referenced by bound(), VMATH_NAMESPACE::Aabb3< T >::extend(), vmtkFrameBufferObject::init(), VMATH_NAMESPACE::Aabb3< T >::intersection(), and vmtkRender3D::maximumDimension().
     {
         return VEC2<T>(::std::max(a.x, b.x), ::std::max(a.y, b.y));
     }
max() [2/3]
template<typename T > VEC3<T> std::max (const VEC3< T > & a, const VEC3< T > & b)
Gets vector containing maximal values of a and b coordinates.
Returns
Vector of maximal coordinates.
Definition at line 3979 of file vmath.h.
References max().
     {
         return VEC3<T>(::std::max(a.x, b.x), ::std::max(a.y, b.y), ::std::max(a.z, b.z));
     }
max() [3/3]
template<typename T > VEC4<T> std::max (const VEC4< T > & a, const VEC4< T > & b)
Gets vector containing maximal values of a and b coordinates.
Returns
Vector of maximal coordinates.
Definition at line 3989 of file vmath.h.
Referenced by max().
     {
         return VEC4<T>(::std::max(a.x, b.x), ::std::max(a.y, b.y), ::std::max(a.z, b.z), ::std::max(a.w, b.w));
     }
min() [1/3]
template<typename T > VEC2<T> std::min (const VEC2< T > & a, const VEC2< T > & b)
Gets vector containing minimal values of a and b coordinates.
Returns
Vector of minimal coordinates.
Definition at line 3939 of file vmath.h.
References min().
Referenced by bound(), VMATH_NAMESPACE::Aabb3< T >::extend(), VMATH_NAMESPACE::Aabb3< T >::intersection(), and registerVolumes().
     {
         return VEC2<T>(::std::min(a.x, b.x), ::std::min(a.y, b.y));
     }
min() [2/3]
template<typename T > VEC3<T> std::min (const VEC3< T > & a, const VEC3< T > & b)
Gets vector containing minimal values of a and b coordinates.
Returns
Vector of minimal coordinates.
Definition at line 3949 of file vmath.h.
References min().
     {
         return VEC3<T>(::std::min(a.x, b.x), ::std::min(a.y, b.y), ::std::min(a.z, b.z));
     }
min() [3/3]
template<typename T > VEC4<T> std::min (const VEC4< T > & a, const VEC4< T > & b)
Gets vector containing minimal values of a and b coordinates.
Returns
Vector of minimal coordinates.
Definition at line 3959 of file vmath.h.
Referenced by min(), and VMATH_NAMESPACE::Aabb3< T >::size().
     {
         return VEC4<T>(::std::min(a.x, b.x), ::std::min(a.y, b.y), ::std::min(a.z, b.z), ::std::min(a.w, b.w));
     }