VMTK: VMATH_NAMESPACE Namespace Reference
VMATH_NAMESPACE Namespace Reference
Classes
class Aabb3
class Matrix3
class Matrix4
class Quaternion
class Vector2
class Vector3
class Vector4
Typedefs
typedef class Vector2< float > Vector2f
Two dimensional Vector of floats.
typedef class Vector2< double > Vector2d
Two dimensional Vector of doubles.
typedef class Vector2< int > Vector2i
Two dimensional Vector of ints.
typedef Vector3< float > Vector3f
Three dimensional Vector of floats.
typedef Vector3< double > Vector3d
Three dimensional Vector of doubles.
typedef Vector3< int > Vector3i
Three dimensional Vector of ints.
typedef Vector4< float > Vector4f
Three dimensional Vector of floats.
typedef Vector4< double > Vector4d
Three dimensional Vector of doubles.
typedef Vector4< int > Vector4i
Three dimensional Vector of ints.
typedef Matrix3< float > Matrix3f
Matrix 3x3 of floats.
typedef Matrix3< double > Matrix3d
Matrix 3x3 of doubles.
typedef Matrix3< int > Matrix3i
Matrix 3x3 of int.
typedef Matrix4< float > Matrix4f
Matrix 4x4 of floats.
typedef Matrix4< double > Matrix4d
Matrix 4x4 of doubles.
typedef Matrix4< int > Matrix4i
Matrix 4x4 of int.
typedef Quaternion< float > Quatf
typedef Quaternion< double > Quatd
typedef Aabb3< float > Aabb3f
typedef Aabb3< double > Aabb3d
Functions
template<typename T >
T radians (T angleInRadians)
bool closeEnough (float a, float b, float eps=epsilon)
Variables
const double epsilon = 4.37114e-05
Typedef Documentation
Aabb3d
typedef Aabb3<double> VMATH_NAMESPACE::Aabb3d
Definition at line 4424 of file vmath.h.
Aabb3f
typedef Aabb3<float> VMATH_NAMESPACE::Aabb3f
Definition at line 4423 of file vmath.h.
Matrix3d
typedef Matrix3<double> VMATH_NAMESPACE::Matrix3d
Matrix 3x3 of doubles.
Definition at line 2310 of file vmath.h.
Matrix3f
typedef Matrix3<float> VMATH_NAMESPACE::Matrix3f
Matrix 3x3 of floats.
Definition at line 2308 of file vmath.h.
Matrix3i
typedef Matrix3<int> VMATH_NAMESPACE::Matrix3i
Matrix 3x3 of int.
Definition at line 2312 of file vmath.h.
Matrix4d
typedef Matrix4<double> VMATH_NAMESPACE::Matrix4d
Matrix 4x4 of doubles.
Definition at line 3339 of file vmath.h.
Matrix4f
typedef Matrix4<float> VMATH_NAMESPACE::Matrix4f
Matrix 4x4 of floats.
Definition at line 3337 of file vmath.h.
Matrix4i
typedef Matrix4<int> VMATH_NAMESPACE::Matrix4i
Matrix 4x4 of int.
Definition at line 3341 of file vmath.h.
Quatd
typedef Quaternion<double> VMATH_NAMESPACE::Quatd
Definition at line 3905 of file vmath.h.
Quatf
typedef Quaternion<float> VMATH_NAMESPACE::Quatf
Definition at line 3904 of file vmath.h.
Vector2d
typedef class Vector2< double > VMATH_NAMESPACE::Vector2d
Two dimensional Vector of doubles.
Definition at line 611 of file vmath.h.
Vector2f
typedef class Vector2< float > VMATH_NAMESPACE::Vector2f
Two dimensional Vector of floats.
Definition at line 609 of file vmath.h.
Vector2i
typedef class Vector2< int > VMATH_NAMESPACE::Vector2i
Two dimensional Vector of ints.
Definition at line 613 of file vmath.h.
Vector3d
typedef Vector3<double> VMATH_NAMESPACE::Vector3d
Three dimensional Vector of doubles.
Definition at line 1198 of file vmath.h.
Vector3f
typedef Vector3<float> VMATH_NAMESPACE::Vector3f
Three dimensional Vector of floats.
Definition at line 1196 of file vmath.h.
Vector3i
typedef Vector3<int> VMATH_NAMESPACE::Vector3i
Three dimensional Vector of ints.
Definition at line 1200 of file vmath.h.
Vector4d
typedef Vector4<double> VMATH_NAMESPACE::Vector4d
Three dimensional Vector of doubles.
Definition at line 1747 of file vmath.h.
Vector4f
typedef Vector4<float> VMATH_NAMESPACE::Vector4f
Three dimensional Vector of floats.
Definition at line 1745 of file vmath.h.
Vector4i
typedef Vector4<int> VMATH_NAMESPACE::Vector4i
Three dimensional Vector of ints.
Definition at line 1749 of file vmath.h.
Function Documentation
closeEnough()
bool VMATH_NAMESPACE::closeEnough (float a, float b, float eps = epsilon) inline
Definition at line 154 of file vmath.h.
Referenced by VMATH_NAMESPACE::Matrix3< T >::getEulerAngles(), and VMATH_NAMESPACE::Matrix4< T >::getEulerAngles().
{
     return (eps > std::abs(a - b));
 }
radians()
template<typename T > T VMATH_NAMESPACE::radians (T angleInRadians) inline
Definition at line 149 of file vmath.h.
References M_PI.
Referenced by VMATH_NAMESPACE::Matrix4< T >::Perspective(), and VMATH_NAMESPACE::Matrix4< T >::Perspective_vmath().
 {
     return angleInRadians * static_cast<T>(180.0/M_PI);
 }
Variable Documentation
epsilon
const double VMATH_NAMESPACE::epsilon = 4.37114e-05
Definition at line 144 of file vmath.h.
Referenced by VMATH_NAMESPACE::Quaternion< T >::slerp().