VMTK: C:/vmtk_Multi-volume_Raycasting/src/vmtkFrameBufferObject.cpp File Reference
vmtkFrameBufferObject.cpp File Reference
#include "vmtkFrameBufferObject.h"
Functions
GLuint bound (const int &min, const int &val, const int &max)
Function Documentation
bound()
GLuint bound (const int & min, const int & val, const int & max)
Definition at line 3 of file vmtkFrameBufferObject.cpp.
References std::max(), and std::min().
Referenced by vmtkFrameBufferObject::init().
 {
   return (GLuint) std::max(min, std::min(max, val));
 }